SparkPost/matchbox

- src/components/Button/Button.module.scss
- src/components/Radio/Group.js
- src/components/Radio/Radio.js
- src/components/Radio/Radio.module.scss
- src/components/index.js
- stories/Radio.js
- stories/index.js
> Radios FAD-5191

- src/components/Table/Table.js
- src/components/Table/TableElements.js
- stories/Table.js
> Table Types

- src/components/Banner/Banner.module.scss
- src/components/Checkbox/Checkbox.js
- src/components/Checkbox/Checkbox.module.scss
- src/components/Radio/Radio.js
- src/components/Radio/Radio.module.scss
- src/components/Select/Select.js
- src/components/Select/Select.module.scss
- src/components/TextField/TextField.js
- src/components/TextField/TextField.module.scss
- src/components/Toggle/Toggle.js
- src/components/Toggle/Toggle.module.scss
- src/components/Toggle/index.js
- src/components/index.js
- src/styles/global.scss
- stories/Checkbox.js
- stories/Radio.js
- stories/Select.js
- stories/TextField.js
- stories/Toggle.js
- stories/index.js
Resolves #16 
Resolves #17 
Resolves #18
> Add Toggles & Add disabled and helpText props to input components

- src/components/Pagination/Pagination.js
- src/components/Pagination/Pagination.module.scss
> Fix pagination prop change, & disable pointer events on selected

- src/icons/index.js
Export the included icon from `lock.js`
> Add `Lock` icon

- src/components/Tooltip/Tooltip.js
- src/components/Tooltip/Tooltip.module.scss
- stories/Tooltip.js
> Add right and offset props to tooltips

- package-lock.json
- package.json
- src/components/Icon/Icon.js
- src/components/TextField/TextField.js
- src/components/TextField/TextField.module.scss
- stories/TextField.js
> Textfield prefix suffix

- src/components/Banner/Banner.js
- stories/Banner.js
Fixes the `action` prop type, as well as supports an array of `actions`
> Fix <Banner  /> PropTypes

- src/styles/global.scss
> Fix ul, ol font styles

- package-lock.json
- stories/Select.js
There was already an example in the "Default", but the value did not match any of the option values.
> Example of <Select /> with a default value

- src/components/Tooltip/Tooltip.js
- src/components/Tooltip/Tooltip.module.scss
- src/components/WithPositioning/index.js
- src/components/WithPositioning/withPositioning.js
- src/components/index.js
- stories/Tooltip.js
> Add withPositioning HOC

- src/components/EmptyState/EmptyState.js
- src/components/EmptyState/EmptyState.module.scss
- src/components/EmptyState/index.js
- src/components/index.js
- src/styles/config/_typography.scss
- stories/EmptyState.js
- stories/index.js
Adds the `EmptyState` component. Cloeses #49
> Add EmptyState

- src/components/Button/Button.module.scss
- src/components/Popover/Popover.js
- src/components/Select/Select.js
- src/components/Tag/Tag.js
- src/components/Tag/Tag.module.scss
- stories/Popover.js
- stories/Select.js
- stories/Tag.js
- stories/Tooltip.js
> Tags, and a few other things

- src/components/Select/Select.js
Need this so I can make certain options "disabled" but good for flexibility
> Add pass-through props for select options

- package-lock.json
- src/components/Popover/Popover.js
- stories/Popover.js
To do sometime after selection is done.
> Added onClose callback support

- src/components/Tabs/Tabs.module.scss
> Fix tabs to not show random scrollbar

- src/components/Tag/Tag.module.scss
- src/components/Tooltip/Tooltip.module.scss
- Fixes Tag spacing
- Fixes Tooltip borders
> Tag spacing & Tooltip borders

- package-lock.json
- package.json
- stories/ActionList.js
- stories/Banner.js
- stories/Button.js
- stories/Checkbox.js
- stories/Datepicker.js
- stories/EmptyState.js
- stories/Grid.js
- stories/Icons.js
- stories/Modal.js
- stories/Page.js
- stories/Pagination.js
- stories/Panel.js
- stories/Popover.js
- stories/ProgressBar.js
- stories/Radio.js
- stories/Select.js
- stories/Snackbar.js
- stories/Table.js
- stories/Tabs.js
- stories/Tag.js
- stories/TextField.js
- stories/Toggle.js
- stories/Tooltip.js
- stories/Welcome.js
- stories/WindowEvent.js
Also closes #60 
Package with the vulnerability is a dep of addon-info. Updated addon-info to latest, and removed deprecated `.addWithInfo` usage. 
Can verify storybook builds correctly with: `npm run build-storybook`
> FAD-6011 Fix vulnerability?

- stories/Checkbox.js
> Fix checkbox story error (#94)

- package-lock.json
- package.json
- src/components/Select/Select.module.scss
> Fixed Select appearance for Firefox

- src/components/index.js
I would like to use the `<Label />` component, please.
> Export Label component

- packages/matchbox-icons/src/IconBase/IconBase.js
See more here: https://css-tricks.com/almanac/properties/v/vertical-align/
> Updates vertical alignment for icons

- packages/matchbox/src/components/Toggle/Toggle.js
- packages/matchbox/src/components/Toggle/Toggle.module.scss
- packages/matchbox/src/components/Toggle/tests/Toggle.test.js
- packages/matchbox/src/components/Toggle/tests/__snapshots__/Toggle.test.js.snap
- stories/action/Toggle.stories.js
> EO-591 Add a compact style Toggle

- packages/matchbox-icons/src/icons/TemplateOutlineFill.js
- packages/matchbox-icons/src/index.js
> TR-1357 New TemplateOutlineFill icon

- config/jest/matchers.js
- config/jest/setup.js
- jest.config.json
- package-lock.json
- package.json
- packages/matchbox/package-lock.json
- packages/matchbox/package.json
- packages/matchbox/src/components/Slider/Slider.js
- packages/matchbox/src/components/Slider/Slider.module.scss
- packages/matchbox/src/components/Slider/index.js
- packages/matchbox/src/components/Slider/tests/Slider.test.js
- packages/matchbox/src/components/Slider/tests/__snapshots__/Slider.test.js.snap
- packages/matchbox/src/components/index.js
- packages/matchbox/src/helpers/event.js
- packages/matchbox/src/helpers/geometry.js
- packages/matchbox/src/helpers/keyEvents.js
- packages/matchbox/src/helpers/math.js
- packages/matchbox/src/helpers/tests/event.test.js
- packages/matchbox/src/helpers/tests/geometry.test.js
- packages/matchbox/src/helpers/tests/math.test.js
- stories/form/Slider.stories.js
- Adds new Slider component
- Bumps icons package
- Updates matchbox react & react-dom to 16.8.6
- Run storybook `npm run start:storybook` at root
- (or link to 2web2ui)
- Document prop types
> UX-103 Add Slider component

- .storybook/webpack.config.js
- package-lock.json
- package.json
- packages/matchbox/package-lock.json
- packages/matchbox/package.json
- packages/matchbox/rollup/config.js
- packages/matchbox/src/components/Banner/Banner.module.scss
- packages/matchbox/src/components/Button/Button.module.scss
- packages/matchbox/src/components/Checkbox/Checkbox.module.scss
- packages/matchbox/src/components/ComboBox/ComboBoxTextField.module.scss
- packages/matchbox/src/components/EmptyState/EmptyState.module.scss
- packages/matchbox/src/components/Error/Error.module.scss
- packages/matchbox/src/components/Label/Label.module.scss
- packages/matchbox/src/components/Page/Page.module.scss
- packages/matchbox/src/components/Pagination/Pagination.module.scss
- packages/matchbox/src/components/Panel/Panel.module.scss
- packages/matchbox/src/components/Radio/Radio.module.scss
- packages/matchbox/src/components/Select/Select.module.scss
- packages/matchbox/src/components/Snackbar/Snackbar.module.scss
- packages/matchbox/src/components/Tabs/Tabs.module.scss
- packages/matchbox/src/components/Tag/Tag.module.scss
- packages/matchbox/src/components/TextField/TextField.module.scss
- packages/matchbox/src/components/Toggle/Toggle.module.scss
- packages/matchbox/src/components/Tooltip/Tooltip.module.scss
- packages/matchbox/src/styles/config/_typography.scss
- packages/matchbox/src/styles/config/_utilities.scss
- packages/matchbox/src/styles/global.scss
**What's Changed**
- Imports `@sparkpost/design-tokens` into workspace and matchbox
- Resolves Sass imports for storybook / rollup
- Adjusts font sizing to match Calibre's smaller footprint
> UX-106 Add Calibre

- packages/matchbox/src/components/Select/Select.js
- packages/matchbox/src/components/Select/tests/__snapshots__/Select.test.js.snap
* Updates the `<Select/>` component wrapping element from a `<fieldset>` to a `<div>`
* Go to http://localhost:9001/?selectedKind=Form%7CSelect&selectedStory=With%20help%20text&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel and verify that the component looks and behaves as expected
> Resolves #199 by replacing the fieldset element with a div

- packages/matchbox-icons/package-lock.json
- packages/matchbox-site/package-lock.json
- packages/matchbox/package-lock.json
- packages/matchbox/src/components/Snackbar/Snackbar.js
- packages/matchbox/src/components/Snackbar/tests/__snapshots__/Snackbar.test.js.snap
> Resolve #195 by adding alert role to Snackbar component

- packages/matchbox/package-lock.json
- packages/matchbox/src/components/ScreenReaderOnly/ScreenReaderOnly.js
- packages/matchbox/src/components/ScreenReaderOnly/ScreenReaderOnly.module.scss
- packages/matchbox/src/components/ScreenReaderOnly/index.js
- packages/matchbox/src/components/ScreenReaderOnly/tests/ScreenReaderOnly.test.js
- packages/matchbox/src/components/ScreenReaderOnly/tests/__snapshots__/ScreenReaderOnly.test.js.snap
- packages/matchbox/src/components/index.js
- packages/matchbox/src/styles/config/_accessibility.scss
- stories/utility/ScreenReaderOnly.stories.js
Resolves #191 
* Added new `<ScreenReaderOnly>` component
* Added supporting unit tests
* Added example to Storybook
* Navigate to http://localhost:9001/?selectedKind=Utility%7CScreenReaderOnly&selectedStory=basic%20example&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel and see that certain content is in the DOM but is not available to sighted users
> Issue #191 screen reader only component

- packages/matchbox/src/components/Banner/Banner.js
- packages/matchbox/src/components/Banner/tests/Banner.test.js
- packages/matchbox/src/components/Banner/tests/__snapshots__/Banner.test.js.snap
* Updated status object to break out the component name and label content
* Check that the appropriate label is being rendered in the DOM on each [Banner Story]()
> Resolve Issue #193 by adding relevant label prop values for each icon in the Banner component

- README.md
Fix style doc path.
Click on the link.
> Update README.md (Fix broken link)

- cypress/integration/Popover.spec.js
- packages/matchbox/src/components/Popover/PopoverContent.js
- packages/matchbox/src/components/Popover/tests/__snapshots__/Popover.test.js.snap
- stories/overlays/Popover.stories.js
- Adds Cypress tests for the Popover component
- Run unit test with `npm run test:unit`
- Run Cypress tests while running storybook with `npm run start:storybook` and `npm run test:e2e:gui` simultaneously
> FE-777 Add Popover cypress tests

- cypress/integration/Expandable.spec.js
- packages/matchbox-site/package-lock.json
- packages/matchbox/src/components/Expandable/Expandable.js
- packages/matchbox/src/components/Expandable/tests/__snapshots__/Expandable.test.js.snap
- unreleased.md
Give your PR a recognizable title. For example: **FE-123: Ticket Title** or **Resolve Issue #123: Description**.
Adds Cypress tests to the Expandable component in matchbox
Run the e2e tests -> `npm run test:e2e:gui`
> FE-775 Add Cypress tests for the Expandable component

- packages/design-tokens/package-lock.json
- packages/design-tokens/package.json
- packages/matchbox/package-lock.json
- packages/matchbox/package.json
Give your PR a recognizable title. For example: **FE-123: Ticket Title** or **Resolve Issue #123: Description**.
What changes does this PR propose? 
Describe any steps that may help reviewers verify changes.
Anything beyond basic unit testing, such as screen-reader usage, or special interactions.
> Publish Design Tokens Beta.16

- packages/matchbox-site/gatsby-config.js
- packages/matchbox-site/package-lock.json
- packages/matchbox-site/package.json
- packages/matchbox-site/src/components/Color/ContrastChecker.js
- packages/matchbox-site/src/components/Color/Palette.js
- packages/matchbox-site/src/components/Elevation/ElevationExample.js
- packages/matchbox-site/src/components/Elevation/index.js
- packages/matchbox-site/src/components/ExternalLink.js
- packages/matchbox-site/src/components/Heading.js
- packages/matchbox-site/src/components/MDXProvider.js
- packages/matchbox-site/src/components/Motion/Easing.js
- packages/matchbox-site/src/components/Motion/Examples.js
- packages/matchbox-site/src/components/Motion/Speed.js
- packages/matchbox-site/src/components/Motion/index.js
- packages/matchbox-site/src/components/tokens/TokenTable.js
- packages/matchbox-site/src/pages/design/elevation.mdx
- packages/matchbox-site/src/pages/design/index.mdx
- packages/matchbox-site/src/pages/design/motion.mdx
- packages/matchbox-site/src/routes/routes.json
- packages/matchbox-site/src/styles/global.scss
Give your PR a recognizable title. For example: **FE-123: Ticket Title** or **Resolve Issue #123: Description**.
What changes does this PR propose? 
Describe any steps that may help reviewers verify changes.
Anything beyond basic unit testing, such as screen-reader usage, or special interactions.
> Document motion elevation

- packages/matchbox/rollup/plugins/reduceClasses.js
- Adds a classname prefix
- Run the build with `cd packages/matchbox` `npm run build`
- View the compiled css assets, and verify the prefix exists
> Prefix classnames so they dont conflict with old classnames

- packages/matchbox/src/components/Expandable/Expandable.js
- packages/matchbox/src/components/Expandable/styles.js
- packages/matchbox/src/components/Panel/Header.js
- packages/matchbox/src/components/Panel/Panel.js
- packages/matchbox/src/components/Panel/Section.js
- packages/matchbox/src/components/Panel/context.js
- packages/matchbox/src/components/Snackbar/Snackbar.js
- Resolved these issues:
```js
(!) Circular dependencies
src/components/Expandable/Expandable.js -> src/components/Expandable/styles.js -> src/components/Expandable/Expandable.js
src/components/Panel/Panel.js -> src/components/Panel/Section.js -> src/components/Panel/Panel.js
src/components/Panel/Panel.js -> src/components/Panel/Header.js -> src/components/Panel/Panel.js
src/components/index.js -> src/components/Snackbar/index.js -> src/components/Snackbar/Snackbar.js -> src/components/index.js
```
- Manually run the matchbox build
- `cd packages/matchbox` `npm run build`
- Verify no warnings appear
> FE-915 Resolve Circular Dependencies

- packages/matchbox/src/components/Page/Page.js
- packages/matchbox/src/components/Page/tests/Page.test.js
- stories/layout/Page.stories.js
- Hard codes Page spacing
- Verify spacing around Page elements
> FE-985 Remove margin props, Add hardcoded spacing

- packages/matchbox/src/components/ComboBox/ComboBox.js
- unreleased.md
- Check displayName and name when validating ComboBox children
- Confirm with storybook
> FE-1000: ComboBoxMenu and ComboBoxTextField not rendering for Hibana

- packages/matchbox-site/package-lock.json
- packages/matchbox-site/package.json
- packages/matchbox-site/src/components/LiveCode/LiveCode.js
- packages/matchbox-site/src/components/LiveCode/LiveCodeContent.js
- packages/matchbox-site/src/components/ResizeContainer/ResizeContainer.js
- packages/matchbox-site/src/pages/components/actionlist.mdx
- packages/matchbox-site/src/pages/components/index.mdx
- packages/matchbox-site/src/styles/global.scss
- Created LiveCode Component
- Created ResizeContainer Component
> FE-1009 Create LiveCode Component

- packages/matchbox/src/components/ComboBox/ComboBoxMenu.js
- packages/matchbox/src/components/Drawer/Drawer.js
- packages/matchbox/src/components/Popover/PopoverOverlay.js
- packages/matchbox/src/components/TextField/TextField.js
- packages/matchbox/src/components/ThemeProvider/theme.js
- packages/matchbox/src/components/Tooltip/Tooltip.js
- packages/matchbox/src/components/Tooltip/TooltipOverlay.js
- packages/matchbox/src/components/Tooltip/tests/Tooltip.test.js
- stories/layout/Box.stories.js
- stories/overlays/Tooltip.stories.js
- unreleased.md
- Adds zindex tokens to theme.js
- Updates components to use theme
Describe any steps that may help reviewers verify changes.
Anything beyond basic unit testing, such as screen-reader usage, or special interactions.
> UX-156 Add zindex tokens to styled system theme

- packages/matchbox-site/src/components/tokens/Token.js
- packages/matchbox-site/src/components/tokens/tokenStyle.js
- Remove scss from Token Component
- Convert to styled components
> UX-194 Update Token Component

- playroom.config.js
> Remove baseurl

- packages/matchbox-site/src/pages/components/toggle.mdx
Adds props, system props and code examples to Toggle Page
- Updated Toggle Page
- Check Toggle Page at `/components/toggle/`
> UX-187 Update content for Toggle Page

- packages/matchbox-site/src/pages/components/windowevent.mdx
- packages/matchbox-site/src/routes/routes.json
> Add windowevent page

- packages/matchbox/src/components/Slider/Slider.js
- packages/matchbox/src/components/WindowEvent/WindowEvent.js
- packages/matchbox/src/helpers/geometry.js
- packages/matchbox/src/helpers/window.js
- packages/matchbox/src/hooks/useWindowEvent.js
- Checks `window` before using it - to support Gatsby's SSR / static build
> Check window before using

- package-lock.json
- packages/matchbox/src/components/Checkbox/Checkbox.js
- packages/matchbox/src/components/Error/Error.js
- packages/matchbox/src/components/HelpText/HelpText.js
- packages/matchbox/src/components/Radio/Radio.js
- Fixes margin left on help text on form components that are not Radio or Checkbox
- Run storybook and verify form components have correct indentation helptext/error
> Fix error and helptext margins

- packages/matchbox-site/package-lock.json
- packages/matchbox-site/package.json
- packages/matchbox-site/src/pages/components/slider.mdx
- packages/matchbox-site/src/routes/routes.json
> Add slider page

- packages/matchbox-site/src/pages/components/page.mdx
- packages/matchbox-site/src/routes/routes.json
> Add Page page

- packages/matchbox-site/src/pages/components/unstyledlink.mdx
- packages/matchbox-site/src/routes/routes.json
> Add unstyledlink page

- packages/matchbox-site/src/components/Heading.js
- packages/matchbox-site/src/components/Prop/Prop.js
- packages/matchbox-site/src/components/SystemProps/SystemPropsTags.js
- packages/matchbox-site/src/pages/components/page.mdx
- packages/matchbox-site/src/pages/components/tooltip.mdx
- packages/matchbox-site/src/routes/routes.json
> Ux-170 Add tooltip page

- packages/matchbox/src/components/Tabs/Tabs.js
- packages/matchbox/src/components/Tabs/styles.js
- packages/matchbox/src/components/Tabs/tests/Tabs.test.js
- unreleased.md
- Fixes tab `disableResponsiveBehavior` rule
> Fix disableResponsiveBehavior rule

- .github/workflows/test.yml
> Try codecov

- packages/matchbox-site/src/components/ResizeContainer/ResizeContainer.js
- packages/matchbox-site/src/pages/components/tabs.mdx
> Force window resize when resize container is moved

- packages/matchbox-site/src/pages/components/button.mdx
- packages/matchbox-site/src/routes/routes.json
> UX-195 Update Button Page

- packages/matchbox-site/src/pages/components/tag.mdx
- packages/matchbox-site/src/routes/routes.json
> Add Tag page

- packages/matchbox-site/src/pages/components/actionlist.mdx
- packages/matchbox-site/src/pages/components/button.mdx
- packages/matchbox-site/src/routes/routes.json
> UX-192 Update ActionList Page

- packages/matchbox/src/components/Banner/styles.js
- Scopes link color override to p, ol, ul within Banners
> UX-235 Banner visited link styles overriding banner buttons

- packages/matchbox/src/components/UnstyledLink/UnstyledLink.js
- packages/matchbox/src/components/UnstyledLink/tests/UnstyledLink.test.js
- unreleased.md
> Add role=button to UnstyledLinks with an onClick

- packages/matchbox-site/package.json
- packages/matchbox-site/src/components/LiveCode/LiveCodeContent.js
- packages/matchbox-site/src/components/Prop/Prop.js
- packages/matchbox-site/src/pages/components/snackbar.mdx
- packages/matchbox-site/src/routes/routes.json
> Add Snackbar page, Add prettier to react-live

- packages/matchbox-site/src/components/LiveCode/LiveCode.js
- packages/matchbox-site/src/pages/components/emptystate.mdx
- packages/matchbox-site/src/routes/routes.json
> Add empty state page

- packages/matchbox-site/src/components/MDXProvider.js
- packages/matchbox-site/src/components/tokens/FilterableTokenTable.js
- packages/matchbox-site/src/components/tokens/TokenTable.js
- packages/matchbox-site/src/components/tokens/TokenTableStyle.js
- packages/matchbox-site/src/components/tokens/TokenUsage.js
- packages/matchbox-site/src/pages/design/tokenreference.mdx
> Adds a search field for token reference table

- packages/matchbox-site/src/pages/components/banner.mdx
- packages/matchbox-site/src/routes/routes.json
> UX-178 Update Banner Page

- packages/matchbox-site/src/pages/components/banner.mdx
- packages/matchbox-site/src/pages/components/checkbox.mdx
- packages/matchbox-site/src/pages/components/emptystate.mdx
- packages/matchbox-site/src/routes/routes.json
> UX-176 Update Checkbox Page

- .github/workflows/build.yml
- .github/workflows/test.yml
> Update gh actions to run on main branch

- lerna.json
> Update lerna config for old branch name

- packages/matchbox-site/src/pages/components/select.mdx
- packages/matchbox-site/src/routes/routes.json
> UX-207 Update Select Page

- packages/matchbox-site/src/pages/components/radio.mdx
- packages/matchbox-site/src/routes/routes.json
> UX-202 Update Radio Page

- .github/labeler.yml
- .github/workflows/labeller.yml
> Add labeller

- packages/matchbox-site/src/pages/design/color.mdx
Corrects title of the teal color scale
> Corrects title of teal scale

- packages/matchbox-site/src/components/LiveCode/LiveCodeContent.js
- packages/matchbox-site/src/pages/components/textfield.mdx
- packages/matchbox-site/src/routes/routes.json
> UX-193 Update TextField Page

- packages/matchbox-site/src/pages/components/checkbox.mdx
- packages/matchbox-site/src/pages/components/panel.mdx
> UX-182 Update Panel Page

- .github/labeler.yml
- packages/matchbox/src/components/Button/Button.js
- packages/matchbox/src/components/Button/styles.js
- packages/matchbox/src/components/Inline/Inline.js
- packages/matchbox/src/components/Inline/styles.js
- packages/matchbox/src/components/Inline/tests/Inline.test.js
- packages/matchbox/src/styles/helpers.js
- stories/layout/Inline.stories.js
- unreleased.md
- Adds button focus styles
- Closes #321 
- Visit button stories, verify focus works as expected
- Visit other stories with embedded buttons, such as Inline, Textfield, Panel
> UX-231 Add Button focus styles

- packages/matchbox/src/components/Drawer/Header.js
- unreleased.md
- Fixes a visual bug with the drawer close button
- Run storybook and verify the drawer close buttons are square and not overflowing
> UX-243 Fixes a visual bug with drawer close button

- .github/workflows/labeller.yml
> Only run labeler on open and reopen of prs

- packages/matchbox-site/src/pages/components/pagination.mdx
- packages/matchbox-site/src/routes/routes.json
> UX-188 Update Pagination Page

- packages/matchbox-site/src/pages/components/table.mdx
- packages/matchbox-site/src/routes/routes.json
> UX-181 Update Table Page

- packages/matchbox-site/src/pages/components/pager.mdx
- packages/matchbox-site/src/routes/routes.json
> UX-199 Update Pager Page

- packages/matchbox-site/src/pages/components/screenreaderonly.mdx
- packages/matchbox-site/src/routes/routes.json
> UX-180 Update ScreenReaderOnly Page

- packages/matchbox-site/src/components/LiveCode/LiveCodeContent.js
- packages/matchbox-site/src/pages/components/combobox.mdx
- packages/matchbox-site/src/routes/routes.json
> U-191 Update ComboBox Page

- cypress/integration/Tooltip.spec.js
- packages/matchbox/src/components/Tooltip/Tooltip.js
- packages/matchbox/src/components/Tooltip/styles.js
- packages/matchbox/src/components/Tooltip/tests/Tooltip.test.js
- unreleased.md
> Resolve Issue #473 Delay Tooltip

- packages/matchbox-site/src/pages/components/expandable.mdx
- packages/matchbox-site/src/routes/routes.json
> UX-209 Update Expandable Page

- packages/matchbox-site/src/pages/components/popover.mdx
- packages/matchbox-site/src/routes/routes.json
> UX-196 Update Popover Page

- packages/matchbox-site/src/pages/components/portal.mdx
- packages/matchbox-site/src/routes/routes.json
> UX-175 Update Portal Page

- packages/matchbox-site/src/components/TypographyExplorer/TypographyExplorer.js
- Fixes the font size button group in the typography explorer – root fontsize is no longer duplicated
> UX-248 Fix typography explorer

- packages/matchbox-site/src/updates/2020/2020-06-24-4.0.1-release.mdx
> Add 4.0.1 release notes

- site/src/updates/2020/2020-06-29-release.mdx
> Remove blank update

- packages/matchbox/src/components/Checkbox/Group.js
- packages/matchbox/src/components/Checkbox/tests/Group.test.js
- packages/matchbox/src/components/OptionalLabel/OptionalLabel.js
- packages/matchbox/src/components/OptionalLabel/index.js
- packages/matchbox/src/components/Radio/Group.js
- packages/matchbox/src/components/Radio/tests/Group.test.js
- packages/matchbox/src/components/Select/Select.js
- packages/matchbox/src/components/Select/tests/Select.test.js
- packages/matchbox/src/components/TextField/TextField.js
- packages/matchbox/src/components/TextField/tests/TextField.test.js
- packages/matchbox/src/components/index.js
- stories/form/Checkbox.stories.js
- stories/form/Radio.stories.js
- stories/form/Select.stories.js
- stories/form/TextField.stories.js
> UX-242 Add Optional Prop to Form Components

- README.md
- lerna.json
- packages/design-tokens/README.md
- packages/matchbox/README.md
> Update all readme files

- packages/matchbox/src/components/Panel/Panel.js
- packages/matchbox/src/components/Panel/styles.js
- packages/matchbox/src/components/Panel/tests/Panel.test.js
- stories/layout/Panel.stories.js
- Adds border, width, height system props to the Panel component
> Add border, width, height system props to Panel

- site/src/components/GatsbyWrappers/Critical.js
- site/src/components/GatsbyWrappers/PageElement.js
- site/src/components/Layout/Global.js
- site/src/components/Layout/Layout.js
> Fix global styles

- site/src/updates/2020/2020-07-02-release.mdx
> Add release notes

- packages/matchbox/rollup/config.js
> Add missing styled-system/css external dependency

- packages/matchbox/src/components/Panel/styles.js
> Remove overflow:hidden from panels

- packages/matchbox/src/components/Checkbox/Checkbox.js
- packages/matchbox/src/components/HelpText/HelpText.js
- packages/matchbox/src/components/Radio/Radio.js
> Resolves #518 - Add 4px margin top to select and textfield help text

- packages/design-tokens/package-lock.json
- packages/matchbox-icons/package-lock.json
- packages/matchbox-icons/package.json
- packages/matchbox/package-lock.json
- packages/matchbox/package.json
- packages/matchbox/rollup/plugins/js.js
- site/package-lock.json
- site/package.json
> Resolve matchbox security dependencies

- lerna.json
- Removed `independent` versioning in favor of `fixed`
- Run `lerna changed` and verify all packages are listed. this means the next version bump will include all packages.
> UX-277 Use fixed versioning

- site/src/updates/2020/2020-07-14-release.mdx
- site/src/updates/2020/2020-07-20-release.mdx
> Add 4.0.10 release notes

- site/src/updates/2020/2020-07-14-release.mdx
- site/src/updates/2020/2020-07-20-release.mdx
> 4.0.10 release

- site/package-lock.json
- site/package.json
- site/src/components/Prop/Prop.js
- site/src/components/SystemProps/SystemPropsTags.js
- site/src/pages/components/columns.mdx
- site/src/pages/components/grid.mdx
- site/src/routes/routes.json
- stories/layout/Columns.stories.js
> Add Columns page

- package-lock.json
- packages/design-tokens/package-lock.json
- packages/design-tokens/package.json
- packages/matchbox/package-lock.json
> Npm audit fix

- config/helpers.js
- packages/design-tokens/tokens/border-width.yml
- packages/matchbox/src/components/Table/Table.js
- packages/matchbox/src/components/Table/TableElements.js
- packages/matchbox/src/components/Table/styles.js
- packages/matchbox/src/components/Table/tests/Table.test.js
- packages/matchbox/src/components/ThemeProvider/theme.js
- site/src/components/SystemProps/data.js
- stories/layout/Table.stories.js
- Adds new `Table.TotalsRow` component
- Run storybook and visit the table components story
- Verify styling is applied correctly to the totals row
> UX-225 Add new Table.TotalsRow component

- packages/design-tokens/package.json
- packages/design-tokens/tokens/sizing.yml
- packages/design-tokens/tokens/spacing.yml
- Adds spacing-900
```yml
- name: spacing-900
value: 10rem
comment: 160px
```
- Run the token build and verify the token is generated
> UX-282 Add spacing-900 token

- packages/matchbox-media/package.json
> UX-294 Make media package public

- packages/matchbox/src/components/Page/Page.js
- packages/matchbox/src/components/Page/tests/Page.test.js
- stories/layout/Page.stories.js
> UX-297 Support color in Page primary action

- site/gatsby-config.js
- site/src/components/Heading.js
- site/src/components/Layout/SideBarLayout.js
- site/src/components/Layout/UpdatesLayout.js
- site/src/components/Layout/Wrapper.js
- site/src/components/Layout/useNavItems.js
- site/src/pages/index.mdx
- site/src/pages/updates.mdx
- site/src/updates/template.js
> Fix layouts

- site/gatsby-config.js
- site/src/components/Layout/Layout.js
- site/src/components/Layout/SideBarLayout.js
- site/src/components/Layout/UpdatesLayout.js
- site/src/components/Layout/useNavItems.js
- site/src/components/MainNavigation/NavItems.js
- site/src/components/Prop/Prop.js
- site/src/components/seo.js
> Fix page title labels, Add site description and keywords

- site/src/components/ExpandableMenuItem/ExpandableMenuItem.js
> Split expandable toggle from links

- site/src/pages/components/stack.mdx
- site/src/routes/routes.json
> UX-307 Add Stack docs page

- site/src/components/GatsbyWrappers/PageElement.js
- site/src/components/seo.js
- site/src/pages/components/inline.mdx
- site/src/routes/routes.json
> UX-308 & UX-317 - Add Inline docs page & Preload Calibre

- site/src/pages/components/box.mdx
- site/src/routes/routes.json
> UX-306 Add Box docs page

- site/src/components/Layout/useNavItems.js
- site/src/components/Prop/Prop.js
- site/src/components/SideNavigation/SideNavigation.js
- site/src/components/SystemProps/SystemPropsTags.js
- site/src/pages/components/actionlist.mdx
- site/src/pages/components/banner.mdx
- site/src/pages/components/button.mdx
- site/src/pages/components/modal-legacy.mdx
- site/src/pages/components/modal.mdx
- site/src/pages/components/panel-legacy.mdx
- site/src/pages/components/panel.mdx
- site/src/pages/components/table.mdx
- site/src/routes/routes.json
- stories/action/ActionList.stories.js
> UX-321 Add 4.1 documentation

- site/src/pages/components/radiocard.mdx
- site/src/pages/updates.mdx
- site/src/routes/routes.json
> UX-309 Add RadioCard docs page

- packages/matchbox/src/components/Layout/SectionTitle.js
- Adds line height to `Layout.SectionTitle`
- Run storybook and verify responsive line height is set on Layout.SectionTitle
> UX-320 Specify Layout.SectionTitle line height

- packages/matchbox/src/components/Skeleton/Skeleton.js
- packages/matchbox/src/components/Skeleton/index.js
- packages/matchbox/src/components/Skeleton/tests/Skeleton.test.js
- packages/matchbox/src/components/index.js
- stories/feedback/Skeleton.stories.js
- Adds 3 new components
- Skeleton.Header
- Skeleton.Box
- Skeleton.Body
- Verify skeleton stories, http://localhost:9001/?path=/story/feedback-skeleton--as-a-heading
> UX-313 Add Skeleton Components

- packages/matchbox/package-lock.json
- packages/matchbox/package.json
- Added `resize-observer-polyfill` to runtime dependencies
- visit https://codesandbox.io/s/dazzling-solomon-ftokm?file=/src/App.js
- change the matchbox version between `4.1.1` and `4.2.0-resize-fix`
> UX-328 Add resize observer polyfill as runtime dependency

- package-lock.json
- packages/matchbox/src/components/Panel/Panel.js
- packages/matchbox/src/components/Panel/tests/Panel.test.js
- stories/layout/Panel.stories.js
Resoves #624 
- Adds support for the `data-id` prop on the `<Panel />`
- Verify via Storybook that `data-id` is properly rendered to the DOM
> Resolves #624 - Add support for data-id for the Panel component

- .stylelintrc
- package-lock.json
- package.json
- packages/matchbox/src/components/Checkbox/styles.js
- packages/matchbox/src/components/Radio/styles.js
- packages/matchbox/src/components/RadioCard/styles.js
- Adds stylint
- Try to commit a css error!
- Double check RadioCards, Radios, and Checkboxes since I had to make css changes there
> UX-303 Add StyleLint

- site/src/components/Layout/Global.js
- site/src/pages/design/illustration.mdx
- site/src/updates/2020/2020-09-10-4.2.0-release.mdx
> Add release notes 4.2.0

- .gitignore
- cypress/integration/Popover.spec.js
- packages/matchbox/src/components/Popover/Popover.js
- packages/matchbox/src/components/Popover/PopoverOverlay.js
- packages/matchbox/src/components/Popover/tests/Popover.test.js
- packages/matchbox/src/components/Table/styles.js
- site/src/pages/components/popover.mdx
This reverts commit f2c77078c4acc5a490630b6e7e289d59ebd8ade0.
> UX-330 Revert UX-314

- packages/matchbox/src/components/Panel/Panel.js
- packages/matchbox/src/components/Panel/SubHeader.js
- packages/matchbox/src/components/Panel/tests/Panel.test.js
- stories/layout/Panel.stories.js
- Created new `Panel.SubHeader` component
- Verify `Panel` stories
> UX-325 Create Panel.SubHeader Component

- site/src/pages/components/hooks.mdx
- site/src/routes/routes.json
> UX-326 Add Hook Documentation

- packages/matchbox/src/components/Pagination/Pagination.js
> Fix breakpoint hook import

- site/src/components/Layout/Global.js
- site/src/pages/components/panel.mdx
- site/src/routes/routes.json
- site/src/updates/2020/2020-09-21-4.3.1-release.mdx
> Update documentation for 4.3.1

- packages/matchbox/src/helpers/window.js
- site/package-lock.json
- site/package.json
- Mocks `matchMedia` when `window` is not defined
- Install the beta version `4.3.2-beta.1`, try to run the site build with `npm run build`
> UX-343 useBreakpoint supports SSR builds

- packages/matchbox/src/components/LabelValue/LabelValue.js
- packages/matchbox/src/components/LabelValue/index.js
- packages/matchbox/src/components/LabelValue/tests/LabelValue.test.js
- packages/matchbox/src/components/index.js
- stories/layout/LabelValue.stories.js
- Adds new component `LabelValue`
- Visit LabelValue stories: http://localhost:9001/?path=/story/layout-labelvalue--vertical-orientation
> UX-331 Add LabelValue component

- packages/matchbox/src/components/Video/Source.js
- packages/matchbox/src/components/Video/Video.js
- packages/matchbox/src/components/Video/index.js
- packages/matchbox/src/components/Video/tests/Video.test.js
- packages/matchbox/src/components/index.js
- stories/media/Videos.stories.js
- stories/media/video.stories.js
- Adds new `Video` and `Video.Source` components
- Visit http://localhost:9001/?path=/story/media-video--basic-video
> UX-327 Video Component

- packages/matchbox/src/components/Tabs/styles.js
- stories/overlays/Modal.stories.js
> UX-344 Fix Tab focus outline overflow bug

- site/src/pages/components/hooks.mdx
- site/src/pages/components/mixins.mdx
- site/src/pages/components/picture.mdx
- site/src/pages/components/video.mdx
- site/src/routes/routes.json
> Picture and video docs

- packages/matchbox/src/components/ActionList/styles.js
- packages/matchbox/src/components/Expandable/styles.js
- packages/matchbox/src/components/Panel/Header.js
- packages/matchbox/src/components/Panel/Panel.js
- packages/matchbox/src/components/Panel/Section.js
- packages/matchbox/src/components/Panel/tests/Panel.test.js
- packages/matchbox/src/components/Popover/styles.js
- packages/matchbox/src/components/Table/styles.js
- packages/matchbox/src/components/ThemeProvider/theme.js
- site/src/components/SystemProps/data.js
- Changed gray-400 borders to gray-300
- Added borders['300'] to theme
- Verify following stories: Panel, ActionList, Table, ListBox, Popover, ComboBox, Expandable
> UX-346 Lower structural border color to gray-300

- packages/matchbox/src/components/EmptyState/EmptyState.js
- packages/matchbox/src/components/EmptyState/List.js
- packages/matchbox/src/components/EmptyState/styles.js
- stories/layout/EmptyState.stories.js
- Added `EmptyState.List` component
- Verify EmptyState stories
> UX-341 EmptyState.List Component

- packages/matchbox/src/components/Slider/Slider.js
- Listen for component resize instead of window resize 
- Verify resize events working correctly on Slider stories
> UX-349 resize Slider on component size change

- site/src/pages/components/hooks.mdx
> Add useBreakpoint docs

- site/src/pages/components/emptystate.mdx
- Added props documentation for EmptyState
- Run the site locally
- Verify the EmptyState docs
> UX-354 document EmptyState props

- cypress/integration/useInView.spec.js
- packages/matchbox/src/hooks/index.js
- packages/matchbox/src/hooks/useInView.js
- stories/utility/useInView.stories.js
- New `useInView` hook
- Verify `useInView` story
> UX-351 create useInView hook

- packages/matchbox/src/components/InlineCode/InlineCode.js
- packages/matchbox/src/components/InlineCode/index.js
- packages/matchbox/src/components/InlineCode/tests/InlineCode.test.js
- packages/matchbox/src/components/index.js
- stories/utility/InlineCode.stories.js
- Created new `InlineCode` Component
- Verify `InlineCode` stories
> UX-359 Create InlineCode Component

- site/src/pages/components/codeblock.mdx
- site/src/routes/routes.json
- Adds CodeBlock component page to design site
- Run the design site locally and verify CodeBlock page
> UX-358 document CodeBlock component

- site/src/pages/components/labelvalue.mdx
- site/src/routes/routes.json
> UX-379 Add LabelValue component docs

- site/src/pages/components/expandable.mdx
> Resolves #694 - Update Expandable docs

- site/src/pages/components/hooks.mdx
> UX-378 Document useInView hook

- packages/matchbox/src/components/Button/Button.js
> UX-374 Omit 'loading' on Buttons

- site/src/pages/components/hooks.mdx
- Document `usePrefersReducedMotion` hook on the design website
- Run the design site locally
- Verify that `usePrefersReducedMotion` is documented at http://localhost:8001/components/hooks#useprefersreducedmotion
> UX-369 document usePrefersReducedMotion hook

- packages/matchbox/src/components/Panel/Header.js
- packages/matchbox/src/components/Panel/SubHeader.js
- packages/matchbox/src/components/Panel/tests/Panel.test.js
> Resolves #714 - Adds semantic tags around Panel Header components

- site/src/pages/components/modal.mdx
- site/src/pages/components/panel.mdx
- site/src/updates/2020/2020-12-09-4.7.0-release.mdx
> Release notes 4.7.0

- packages/matchbox/src/components/Banner/Banner.js
- packages/matchbox/src/components/Banner/styles.js
- Fixes muted banner styles, was missing a semicolon
- Run storybook and visit: http://localhost:9001/?path=/story/feedback-banner--small-banner
> UX-406 Fix muted banner styles

- packages/matchbox/src/components/Inline/Inline.js
- packages/matchbox/src/components/Inline/styles.js
- site/src/pages/components/inline.mdx
- stories/layout/Inline.stories.js
- Adds a new prop `alignY` to the Inline component to vertically align children
- Visit: http://localhost:9001/?path=/story/layout-inline--vertical-alignment
- Verify vertical alignment works
> UX-408 Add alignY prop to Inline

- packages/matchbox/src/components/EmptyState/Image.js
- packages/matchbox/src/components/EmptyState/List.js
> UX-410 Make empty state image container responsive

- site/src/components/Layout/Global.js
- site/src/pages/components/actionlist.mdx
- site/src/pages/design/actionable-language.mdx
- site/src/routes/routes.json
> UX-385 Add ActionList usage and new Content section

- packages/matchbox/src/components/Modal/Footer.js
- Fixes an incorrect `cloneElement` in Modal.Footer
- Visit http://localhost:9001/?path=/story/overlays-modal--open
- Verify the Modal renders with 0, 1, 2, and 3 buttons
> Hotfix - Fix modal button clone

- .github/workflows/codeql-analysis.yml
- Adds the GH workflow template for codeql scanning
- Visit the Checks tab and verify the code scan is triggered properly (its blank because this is the first run): https://github.com/SparkPost/matchbox/pull/731/checks
> UX-413 Add code scanning

- packages/matchbox/package-lock.json
- packages/matchbox/package.json
- Uninstalls an unused matchbox dependency to resolve a security vulnerability
- Not much to verify, verify the checks pass?
> UX-417 Uninstall unused react-syntax-highlighter

- site/src/updates/2021/20201-02-04-4.8.0-release.mdx
> Add 4.8.0 release notes

- package-lock.json
- package.json
- packages/design-tokens/package-lock.json
- packages/design-tokens/package.json
- packages/matchbox/src/components/Button/tests/__snapshots__/utils.test.js.snap
- Resolves:
- node-notifier: https://github.com/SparkPost/matchbox/security/dependabot/package-lock.json/node-notifier/open 
- highlight.js: https://github.com/SparkPost/matchbox/security/dependabot/packages/design-tokens/package-lock.json/highlight.js/open
- Does NOT resolve (unable to update since parent dependencies haven't patched them yet):
- ecstatic: https://github.com/SparkPost/matchbox/security/dependabot/package-lock.json/ecstatic/open
- immer: https://github.com/SparkPost/matchbox/security/dependabot/package-lock.json/immer/open
- socket.io: https://github.com/SparkPost/matchbox/security/dependabot/site/package-lock.json/socket.io/open
- Verify the package-lock changes are sufficient to resolve the dependabot alerts
- Verify tests and builds work
> UX-436 Resolve dependabot vulnerabilities

- packages/matchbox/src/components/Button/styles.js
- stories/action/Button.stories.js
- Centers spinner on `fullWidth` `<Button>`
- Verify Button Loading [story](http://localhost:9001/?path=/story/action-button--loading)
> UX-427 Fix full width button loading spinner positioning

- package-lock.json
- package.json
- Upgrades libby-react which resolves https://github.com/SparkPost/matchbox/security/dependabot/package-lock.json/immer/open
- Runs `npm audit fix` to resolve: https://github.com/SparkPost/matchbox/security/dependabot/package-lock.json/prismjs/open
- Run libby, verify runtime errors render the overlay correctly
- Verify checks pass
> UX-471 & UX-473 Resolve immer and prismjs vulnerabilities

- site/src/pages/components/emptystate.mdx
- Documents EmptyState.Media
- Removes EmptyState.Image documentation
- Verify EmptyState documentation http://localhost:8001/components/emptystate#emptystate.header-api
> UX-426 Document EmptyState.Media component and remove EmptyState.Image from docs

- packages/matchbox/src/components/Skeleton/Skeleton.js
- Changes `Skeleton` background color from `color_gray_200` to `color_gray_300`
- Verify `Skeleton` stories http://localhost:9001/?path=Skeleton__all-together&source=false
> UX-475 darken skeleton background color from gray_200 to gray_300

- site/package-lock.json
- site/package.json
- Upgrades gatsby, matchbox, and styled-component dependencies in the site
- Resolves this vulnerability: https://github.com/SparkPost/matchbox/security/dependabot/site/package-lock.json/socket.io/open
- Reinstall site dependencies
- Run the site, verify it all works
> UX-476 Resolve socket.io security vulnerability

- site/src/pages/components/inline.mdx
> Description fix for <Inline /> component

- site/src/pages/components/timelinetabs.mdx
- site/src/routes/routes.json
- Adds documentation for `TimelineTabs` and `TimelineTabs.Tab` to design.sparkpost.com
- Verify `TimelineTabs` page http://localhost:8001/components/timelinetabs
> UX-466 Document TimelineTabs component

- cypress/integration/ListBox.spec.js
- libby/form/ListBox.lib.js
- packages/matchbox/src/components/ListBox/ListBox.js
- Removes spreading of unknown ListBox props
- Verify no additional props are used in app: https://proply-2web2ui.vercel.app/
> UX-456 Remove spreading of unknown ListBox props

- packages/matchbox/src/components/Modal/Modal.js
> UX-480 Remove spreading of unknown Modal props

- site/src/pages/design/color.mdx
> UX-488 Update container border color

- cypress/integration/Badge.spec.js
- libby/feedback/Badge.lib.js
- packages/design-tokens/tokens/font-size.yml
- packages/matchbox/src/components/Badge/Badge.js
- packages/matchbox/src/components/Badge/index.js
- packages/matchbox/src/components/ThemeProvider/theme.js
- packages/matchbox/src/components/index.js
- Adds new `Badge` component
- Adds new `font-size-50` token
- Visit http://localhost:9001/?path=Badge__colors&source=false
- Verify all Badge variants work as expected
> UX-477 Add Badge Component, Add new font-size token

- cypress/integration/Table.spec.js
- libby/layout/Table.lib.js
- packages/matchbox/src/components/Table/SortButton.js
- packages/matchbox/src/components/Table/Table.js
- packages/matchbox/src/components/Table/styles.js
- Adds new `Table.SortButton` component
- Run libby with `npm run start:libby`
- Visit http://localhost:9001/?path=Table__all-table-components&source=false
- Verify functionality works as expected
- Verify the component matches the mocks: https://sparkpost.invisionapp.com/console/Table-Header-Sortable-Button-ckm3xhjjy019n01v2f70wc4jk/ckmf5lg4c008n01xxghkwd3vt/play
> UX-484 Add Table.SortButton Component

- config/test-utils.js
- packages/matchbox/src/components/Badge/tests/Badge.test.js
- Writes unit tests for the Badge component using RTL
- Verify unit tests pass
> UX-499 Harden Badge unit testing

- packages/matchbox/src/components/Table/SortButton.js
- Fixes the wrapping of Table SortButton
- Run libby and visit http://localhost:9001/?path=Table__all-table-components&source=false
- Verify wrapping behavior is expected
> 5.1.1-Hotfix: Fix wrapping of content in Sort Button

- packages/matchbox/src/components/Button/Button.js
- packages/matchbox/src/components/Button/tests/utils.test.js
- packages/matchbox/src/components/Button/utils.js
- Resolves a circular dependency in the Button component
- Run the matchbox package build
- Verify the build does not output a warning about a circular dependency
```bash
cd packages/matchbox
npm run build
```
> UX-512 Resolve circular dependency

- package-lock.json
- package.json
- site/package-lock.json
- site/package.json
- Updates dependencies for `xmlhttprequest-ssl`
- Verify `xmlhttprequest-ssl` is at least `1.6.2` in all package-lock.json files
> UX-528 Resolve xmlhttprequest-ssl vulnerabilities

- libby/form/ListBox.lib.js
- libby/form/RadioCard.lib.js
- packages/matchbox/src/components/ListBox/ListBox.js
- packages/matchbox/src/components/ListBox/tests/ListBox.test.js
- packages/matchbox/src/components/RadioCard/RadioCard.js
- packages/matchbox/src/components/RadioCard/tests/RadioCard.test.js
- Adds `data-track` to ListBox and RadioCard
- Run Libby, or run the unit tests
- Verify `data-track` is passed through
> UX-531 Support tracking on ListBox and RadioCard

- libby/icons/Icons.lib.js
> UX-537 Add an icon search

- cypress/integration/ListBox.spec.js
- libby/form/ListBox.lib.js
- packages/matchbox/src/components/ListBox/ListBox.js
> UX-538 Fix controlled Listboxes

- packages/design-tokens/formats/meta.js.js
- packages/design-tokens/formats/utils.js
- packages/design-tokens/tests/__snapshots__/tokens.test.js.snap
- packages/design-tokens/tests/tokens.test.js
> Add system prop names to meta

- packages/matchbox/src/components/Label/Label.js
- packages/matchbox/src/components/Radio/tests/Group.test.js
> UX-567 Fix floated optional labels

- libby.config.js
- libby/utility/useInView.lib.js
- package-lock.json
- package.json
- packages/design-tokens/package-lock.json
- packages/matchbox-icons/package-lock.json
- packages/matchbox-icons/package.json
- packages/matchbox/package-lock.json
- packages/matchbox/package.json
> UX-587 Resolve security dependabot alerts

- package-lock.json
- package.json
> UX-590 Update libby to fix live reloading

- README.md
- packages/matchbox-icons/readme.md
- Update the readme with the correct link for getting started
- Verify the link points to the getting started guide on design.sparkpost.com
> Update readme with correct link for matchbox getting started guide

- packages/matchbox-icons/src/icons/CloseCircleOutline.js
- packages/matchbox-icons/src/index.js
> UX-601 Add CloseCircleOutline icon

- libby.config.js
- libby/layout/Page.lib.js
- package-lock.json
- package.json
- packages/matchbox/src/components/Page/Page.js
- packages/matchbox/src/components/Tabs/styles.js
- packages/matchbox/src/components/Tabs/tests/Tabs.test.js
- Restyles Tabs and Page components to match these mocks: https://www.figma.com/file/juWNBofvmmQBLABf2PPBWY/Page-Header-Rework?node-id=3%3A588
- Visit the this story with both Page and Tabs: http://localhost:9001/?path=Page__with-Tabs
- Verify Tab styling and page header typography matches mocks
> UX-599 Restyle Tabs and Page header components

- .github/workflows/e2e.yml
- .github/workflows/unit.yml
> UX-604 Run unit and e2e tests concurrently

- packages/matchbox/package-lock.json
- packages/matchbox/package.json
> (Hotfix) Fix e2e tests

- libby/form/ListBox.lib.tsx
- packages/matchbox/src/components/ActionList/Action.tsx
- packages/matchbox/src/components/Checkbox/styles.ts
- packages/matchbox/src/components/ListBox/ListBox.tsx
- packages/matchbox/src/components/ListBox/Option.tsx
- packages/matchbox/src/components/ListBox/index.tsx
- packages/matchbox/src/components/ListBox/styles.ts
- packages/matchbox/src/components/ListBox/useOptionConstructor.tsx
- Converts `ListBox` component to typescript
- Verify tests pass and stories are correct
> UX-634 Convert ListBox to typescript

- libby/overlays/Modal.lib.tsx
- packages/matchbox/src/components/Drawer/Drawer.tsx
- packages/matchbox/src/components/Modal/Content.tsx
- packages/matchbox/src/components/Modal/Footer.tsx
- packages/matchbox/src/components/Modal/Header.tsx
- packages/matchbox/src/components/Modal/Modal.tsx
- packages/matchbox/src/components/Modal/context.js
- packages/matchbox/src/components/Modal/context.ts
- packages/matchbox/src/components/Modal/index.ts
- packages/matchbox/src/components/Modal/styles.js
- packages/matchbox/src/components/Panel/Panel.tsx
- packages/matchbox/src/components/Panel/index.ts
- packages/matchbox/src/components/Popover/Popover.tsx
- packages/matchbox/src/components/Portal/Portal.tsx
- packages/matchbox/src/components/Portal/index.ts
- packages/matchbox/src/components/Tooltip/Tooltip.tsx
- packages/matchbox/src/components/Tooltip/TooltipOverlay.tsx
> UX-635 Convert modal to typescript

- libby/form/Radio.lib.tsx
- packages/matchbox/src/components/Radio/Group.tsx
- packages/matchbox/src/components/Radio/Radio.tsx
- packages/matchbox/src/components/Radio/index.js
- packages/matchbox/src/components/Radio/index.ts
- packages/matchbox/src/components/Radio/styles.ts
- packages/matchbox/src/components/Radio/tests/Radio.test.js
> UX-645 convert Radio to typescript

- packages/matchbox/src/hooks/useInputDescribedBy.ts
> UX-669 Convert useInputDescribedBy to typescript

- packages/matchbox/src/components/Slider/Slider.tsx
- packages/matchbox/src/components/Slider/index.ts
- packages/matchbox/src/components/Slider/styles.ts
- Converts `Slider` to typescript
- Verify the slider stories work as expected
> UX-650 Convert Slider to typescript

- packages/matchbox/src/helpers/types.ts
- packages/matchbox/src/hooks/useDrawer.ts
> UX-668 Convert useDrawer to typescript

- packages/matchbox/src/hooks/useBreakpoint.ts
> UX-666 😈 Convert useBreakpoint to typescript

- packages/matchbox/src/components/Popover/Popover.tsx
- packages/matchbox/src/helpers/focus.ts
> UX-680 Convert focus helpers to typescript

- packages/matchbox/src/hooks/useWindowEvent.ts
> UX-676 Convert useWindowEvent to typescript

- packages/matchbox/src/helpers/geometry.ts
> UX-681 convert geometry helpers to typescript

- packages/matchbox/src/hooks/useModal.ts
> UX-671 convert useModal to typescript

- packages/matchbox/src/helpers/array.ts
> UX-677 Convert array helpers to typescript

- packages/matchbox/src/helpers/string.js
- packages/matchbox/src/helpers/string.ts
> UX-686 convert string helper to typescript

- packages/matchbox/src/helpers/props.ts
> UX-684 Convert prop helpers to typescript

- packages/matchbox-icons/src/IconBase/IconBase.tsx
> Fix the icons build

- packages/matchbox/src/components/Pager/Next.tsx
- packages/matchbox/src/components/Pager/Previous.tsx
- Pager buttons now match the sizing of Pagination buttons
- Visit the Pagination stories: http://localhost:9001/?path=Pagination__with-lots-of-pages
- Verify the buttons are all the same size
> UX-695 Fix Pager button sizing

- packages/matchbox/package.json
> UX-704 Update icons peer dependency in Matchbox

- packages/matchbox/package.json
> UX-704 Update matchbox peer dependencies

- cypress/regression/Button.spec.js
- libby/regression/Buttons.lib.tsx
- Adds a new story for Button regression testing
- Run Libby
- Run `npm run test:regression:headless` to run Percy snapshots
- Log into Percy and verify the snapshots are uploaded
> UX-711 Take Percy snapshot of Button component

- packages/matchbox/src/components/InlineCode/InlineCode.tsx
- Update InlineCode to match new mockups: https://www.figma.com/file/e3MkJzIFKhE0NH85miqDVF/Markdown-Files?node-id=6%3A1792
- Run libby, and visit: http://localhost:9001/?path=InlineCode__basic-example
- Verify the styles are correct
> UX-726 Modify InlineCode styling

- packages/design-tokens/tests/__snapshots__/tokens.test.js.snap
- packages/design-tokens/tests/tokens.test.js
- Snapshots all generated `scss` and `css` design-token files
- Verify the snapshots match the generated output
> UX-746 Snapshot all generated design token files

- packages/matchbox-css/.gitignore
- packages/matchbox-css/index.scss
- packages/matchbox-css/package-lock.json
- packages/matchbox-css/package.json
- packages/matchbox-css/tokens/font-size.scss
- Adds new @sparkpost/matchbox-css library
- Adds css classes for font-size which handles media queries and various interactive states
- Run `npm run compile` locally and verify that all the necessary classes were created correctly using the font-size tokens
> UX-732 Create new matchbox-css library

- packages/matchbox-css/index.scss
- packages/matchbox-css/tokens/color.scss
- packages/matchbox-css/tokens/font-size.scss
- Creates color design token utility classes at each breakpoint and for each interaction type
- `npm run compile` locally and make sure all colors are being created as classes correctly
> UX-733 Create color utility classes

- packages/matchbox-css/index.scss
- packages/matchbox-css/tokens/border-radius.scss
- packages/matchbox-css/tokens/border-width.scss
- packages/matchbox-css/tokens/box-shadow.scss
- packages/matchbox-css/tokens/font-family.scss
- packages/matchbox-css/tokens/font-weight.scss
- packages/matchbox-css/tokens/line-height.scss
- packages/matchbox-css/tokens/motion-duration.scss
- packages/matchbox-css/tokens/motion-ease.scss
- packages/matchbox-css/tokens/z-index.scss
- Adds typography classes
- Adds elevation classes
- Adds motion classes
- Adds z-index classes
- Adds border classes
- `npm run compile` locally and verify the classes are created correctly
> UX-734, UX-736, UX-737, UX-738, UX-739, UX-740, UX-741 Token classes

- packages/matchbox/src/components/Button/styles.ts
- Fixes the white button variant text color to match UI kit
- Visit: http://localhost:9001/?path=Button__all-variants
- Verify the button text color
> UX-765 Fix white button text color

- package-lock.json
- package.json
> Upgrade libby & npm audit fix

- CHANGELOG.md
- packages/cra-template-matchbox/template.json
> UX-767 Publish 7.0.0

- packages/matchbox/package-lock.json
- packages/matchbox/package.json
> Hotfix 7.0.0

- package-lock.json
- packages/matchbox-css/package-lock.json
- packages/next-template-matchbox/package-lock.json
- packages/next-template-matchbox/package.json
> UX-775 Resolve a few security vulnerabilities

- cypress/regression/QueryCard.spec.js
- libby/form/QueryCard.lib.tsx
- libby/regression/QueryCard.lib.tsx
- packages/matchbox/src/components/QueryCard/Group.tsx
- packages/matchbox/src/components/QueryCard/Legend.tsx
- packages/matchbox/src/components/QueryCard/Operator.tsx
- packages/matchbox/src/components/QueryCard/QueryCard.tsx
- packages/matchbox/src/components/QueryCard/Subtitle.tsx
- packages/matchbox/src/components/QueryCard/Title.tsx
- packages/matchbox/src/components/QueryCard/index.ts
- packages/matchbox/src/components/index.tsx
- Adds `QueryCard` component
- Run libby locally and visit http://localhost:9001/?path=QueryCard__renders-correctly-with-all-components
- Verify the component matches mocks and works correctly
> UX-774 Add QueryCard Component

- cypress/integration/Progress.spec.js
- libby/navigation/Progress.lib.tsx
- package-lock.json
- package.json
- packages/matchbox/src/components/Progress/Progress.tsx
- packages/matchbox/src/components/Progress/Step.tsx
- packages/matchbox/src/components/Progress/index.ts
- packages/matchbox/src/components/Progress/tests/Progress.test.js
- packages/matchbox/src/components/index.tsx
- packages/matchbox/src/helpers/tests/theme.test.js
- packages/matchbox/src/helpers/theme.ts
- Adds new Progress component
- Run Libby and visit: http://localhost:9001/?path=Progress__basic-usage
- Verify the component works correctly and matches the mocks here:
- https://www.figma.com/file/uKubC4RT18p0MZnGSJI1KA/Progress?node-id=4%3A38
> UX-769 Add Progress Component

- packages/matchbox/src/components/Panel/SubHeader.tsx
- change font size and line height from 200 to 300 on Panel.Subheader
- Verify Panel.Subheader font size is correct
> UX-785 update font size on Panel.Subheader

- packages/matchbox/src/components/Banner/index.tsx
> Fix Banner types export

- packages/matchbox/src/components/ActionList/Action.tsx
- packages/matchbox/src/components/Tabs/useTabConstructor.tsx
> Fix Actionlist.Action types export

- packages/matchbox/src/components/ActionList/ActionList.tsx
- packages/matchbox/src/components/ListBox/ListBox.tsx
- packages/matchbox/src/components/Popover/Popover.tsx
- packages/matchbox/src/components/Slider/Slider.tsx
- packages/matchbox/src/components/TextField/TextField.tsx
- packages/matchbox/src/helpers/ref.ts
> fix: Fix combining legacy refs

- libby/feedback/Banner.lib.tsx
- packages/matchbox/src/components/Banner/Banner.tsx
- packages/matchbox/src/components/Banner/styles.ts
- packages/matchbox/src/components/Banner/tests/Banner.test.js
> UX-792 - feat(Banner): add promo variant

- .changeset/clean-eggs-agree.md
- libby/feedback/Badge.lib.tsx
- packages/matchbox/src/components/Badge/Badge.tsx
1. Create a changeset with `npx changeset`
1. Ensure the changeset in the `.changeset` directory includes a descriptive summary
1. Commit the changeset to your pull request
> fix(Badge): pass through all div props

- .changeset/dull-ads-march.md
- package-lock.json
- packages/matchbox-css/index.scss
- packages/matchbox-css/package.json
- packages/matchbox-css/scripts/compile.js
1. Create a changeset with `npx changeset`
1. Ensure the changeset in the `.changeset` directory includes a descriptive summary
1. Commit the changeset to your pull request
> refactor(css): use dart-sass instead of node-sass

- .changeset/fair-ants-knock.md
- libby/form/ListBox.lib.tsx
- packages/matchbox/src/components/ListBox/ListBox.tsx
- packages/matchbox/src/components/ListBox/Option.tsx
- packages/matchbox/src/components/ListBox/useOptionConstructor.tsx
- Adds JSX support inside ListBox Option children
1. Create a changeset with `npx changeset`
1. Ensure the changeset in the `.changeset` directory includes a descriptive summary
1. Commit the changeset to your pull request
> feat(ListBox): allow JSX inside options
