SparkPost/matchbox

src/components/TextField/TextField.js
The `name` prop on `TextField > input` was being set to undefined for all TextFields. This passes the prop through correctly.
=> Pass input name from props correctly

src/components/Connect/Connect.module.scss, src/components/Pagination/Pagination.module.scss, src/components/Select/Select.module.scss, stories/Pagination.js, stories/TextField.js
Closes #57 
Could not find a way to correctly disable box-shadow or apply border-radius 0 when using `Tooltip` with `Select` or `Button`. So instead i'm just adding box-shadows to Selects so at least they'll look the same as Buttons ¯\_(ツ)_/¯
- Fixes Connect's border-radius `!important` overrides
- Fixes Pagination button widths
=> Add box shadows to select

src/components/EmptyState/EmptyState.js, src/components/Page/Page.js
@jonambas what do you think of doing something like this, so you can define empty state config on a Page element? It would inherit the title and primary action unless you override them in the empty state config there...
```jsx
<Page 
primaryAction={primaryAction}
title="API Keys"
empty={{
test: !error && list.length === 0,
title: 'Create an API Key'
}}
/>
```
=> Idea around making empty state something you can define on a Page

src/components/Select/Select.js, stories/Select.js
To avoid possible problems with validation, this PR removes the default value (which was `_placeholder`) for placeholder `<option/>` item and allows to set custom values. So, by default, value for placeholder `<option/>` will be empty but can set to a desired value using `placeholderValue` prop.
=> Select placeholder value

src/components/Popover/Popover.js, src/components/Popover/Popover.module.scss, src/components/Tooltip/Tooltip.js, src/components/Tooltip/Tooltip.module.scss, stories/Popover.js, stories/Tooltip.js
Adds `top`, `left`, `right`, `bottom` bool props to `Popover`
Reverses Tooltip `left` & `right` logic
=> Add positioning support for popovers

src/components/Error/Error.js, src/components/Error/Error.module.scss, src/components/Label/Label.js, src/components/TextField/TextField.js, stories/TextField.js
Fixed size forms suffer "pop" as they reflow when components are shown or hidden conditionally. This PR is meant to deal with some of that in context with the in-app support form.
It's tricky to cleanly set `resize: none` on `<textarea />` elements. This PR adds a `resize` prop to mirror the HTML attribute.
- Use `htmlResize` as prop name to match other React HTML props? (e.g. htmlFor)
- Default to `resize: none` instead of the current behaviour preserving `resize: both`?
Fixed size forms containing form components pop when their `Error` components are rendered. To resolve, this PR includes the following:
- `Error` supports an `inline` prop to force `display: inline`.
- `Label` components now render their children so we can put errors under `Labels`.
- `TextArea` supports an …
=> FAD-5588: Better support for fixed size form layouts

src/components/Error/Error.js, src/components/Error/Error.module.scss, src/components/TextField/TextField.js, src/components/TextField/TextField.module.scss
- `TextField` accepts `inlineErrors` boolean prop
- `TextFields` with `inlineErrors=true`:
- render errors inside their `Labels`
- give their `Errors` a styled `<span/>` as their wrapper
- `Errors` accept `wrapper` component prop
Added a `TextField` story to demo inline errors.
=> FAD-5588: Inline errors for TextField

src/components/Checkbox/Checkbox.module.scss, src/components/Radio/Radio.module.scss, src/components/Select/Select.module.scss, src/components/TextField/TextField.module.scss
I adjusted the help text in the dev console, it was at 0.1666667rem and moving it to 0.5rem made it look good, I think. Converted the numbers and I think this does the right thing.
=> Better help text spacing for text fields

src/components/Select/Select.module.scss
=> Fix height of a connected select

src/components/Select/Select.js, src/components/Snackbar/Snackbar.js, src/components/Snackbar/Snackbar.module.scss, stories/Select.js, stories/Snackbar.js
- Adds optional `maxWidth` prop to Snackbar for large chunks of text
- Addresses #113
=> FAD-6286: resizable Snackbar, numeric Select values

packages/matchbox/package-lock.json, packages/matchbox/package.json, packages/matchbox/src/components/ActionList/ActionList.js, packages/matchbox/src/components/Button/utils.js, packages/matchbox/src/components/Page/Page.js, packages/matchbox/src/components/Popover/Popover.js, packages/matchbox/src/components/Popover/PopoverOverlay.js, packages/matchbox/src/components/Popover/tests/Popover.test.js, packages/matchbox/src/components/Popover/tests/__snapshots__/Popover.test.js.snap, packages/matchbox/src/components/Tag/Tag.module.scss, packages/matchbox/src/helpers/array.js, packages/matchbox/src/helpers/tests/__snapshots__/array.test.js.snap, packages/matchbox/src/helpers/tests/array.test.js, stories/action/ActionList.stories.js, stories/feedback/Tag.stories.js, stories/layout/Page.stories.js, stories/layout/Panel.stories.js
**Popover**
- Repositioning event handler is no longer called unless the Popover is open
**Panel**, **ActionList**, **Page**
- Props that accept an array of actions, such as Panel or ActionList `actions` or Page `secondaryActions`, will no longer render any items if the key`visible` is provided with a falsey value.
- Each action will be displayed by default without this key.
```js
// Will only render the actions 'a' and 'c'
<Panel.Section actions={[
{ content: 'a', visible: true },
{ content: 'b', visible: false },
{ content: 'c' }
]} />
```
=> Visible action key

packages/matchbox/src/components/EmptyState/EmptyState.js, packages/matchbox/src/components/EmptyState/EmptyState.module.scss, packages/matchbox/src/components/EmptyState/tests/__snapshots__/EmptyState.test.js.snap
Wrap the secondary action (a link) under the button.
=> Wrap empty state secondary action

packages/matchbox/src/components/Pagination/Pagination.js, packages/matchbox/src/components/Pagination/tests/Pagination.test.js
Pagination's `cWRP` method triggered `setState`, which was referencing stale props. This caused `hasNext` to be incorrectly evaluated.
=> EO-624 Update pagination lifecycle methods

packages/matchbox/src/components/Popover/Popover.module.scss, packages/matchbox/src/components/Popover/PopoverContent.js, packages/matchbox/src/components/Popover/PopoverOverlay.js, packages/matchbox/src/components/Popover/tests/Popover.test.js, packages/matchbox/src/components/Popover/tests/__snapshots__/Popover.test.js.snap
I published a "fix" for this previously in `3.3.8`, but I think this is a more correct solution.
=> FE-574 Do not position popovers unless open

packages/matchbox/src/components/Radio/Radio.js, packages/matchbox/src/components/Radio/Radio.module.scss, packages/matchbox/src/components/Radio/tests/__snapshots__/Radio.test.js.snap, stories/form/Radio.stories.js
Replaces Radio's css circles with SVGs.
```bash
cd packages/matchbox
npm run build
npm link
npm link @sparkpost/matchbox
npm run start
```
=> FE-633 Replace radios with SVGs

packages/matchbox/package-lock.json, packages/matchbox/package.json, packages/matchbox/src/components/Expandable/Expandable.js, packages/matchbox/src/components/Expandable/Expandable.module.scss, packages/matchbox/src/components/Expandable/index.js, packages/matchbox/src/components/Expandable/tests/Expandable.test.js, packages/matchbox/src/components/Expandable/tests/__snapshots__/Expandable.test.js.snap, packages/matchbox/src/components/index.js, packages/matchbox/src/helpers/keyEvents.js, stories/layout/Expandable.stories.js
Props:
```js
// Default open state when not controlled
defaultOpen: Proptypes.bool,
// Optional React node for an image or icon. Works best with an SVG optimized for 40x40.
icon: Proptypes.node,
// Required for accessilibty between header and content
id: Proptypes.string.isRequired,
// Pass a boolean to control open state
open: Proptypes.bool,
// Optional, but required when controlling open state
onToggle: Proptypes.func,
// Optional content area beneath header title
subtitle: Proptypes.node,
// Main header title content
title: Proptypes.node.isRequired
```
=> UX-123 Add Expandable component

packages/matchbox/package-lock.json, packages/matchbox/src/components/Tag/Tag.js, packages/matchbox/src/components/Tag/tests/Tag.test.js, packages/matchbox/src/components/Tag/tests/__snapshots__/Tag.test.js.snap
Resolves #197
* Added new `handleKeydown` method to enable spacebar handling
* Added `role="button"` and an arbitrary value to the `to` prop to allow keyboard focusing
* Added supporting test for 
* Go to http://localhost:9001/?selectedKind=Feedback%7CTag&selectedStory=with%20remove%20action&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel
* Click immediately before the tag component instance, hit the tab key and the button should have focus
* Hit the spacebar or enter key when focusing on the remove button and the action logger should show the mock function
=> Resolves #197 tag component keyboard focusable remove button

__mocks__/react.js, packages/matchbox/src/components/Slider/Slider.js, packages/matchbox/src/components/Slider/Slider.module.scss, packages/matchbox/src/components/Slider/tests/Slider.test.js, packages/matchbox/src/components/Slider/tests/__snapshots__/Slider.test.js.snap, stories/form/Slider.stories.js
What's Changed:
- Add Slider prop `ticks`
- Resolves #201
Sample Usage
```js
<Slider value={75} ticks={{
0: '0',
50: '50',
25: 'Recommended',
100: '100',
}} />
```
=> UX-137 Add Slider ticks

packages/matchbox/src/components/Button/Button.module.scss
Resolves #231 
- Updated CSS to target specific CSS properties that should be animated
- Verify existing hover states for the button component -> http://localhost:9001/?selectedKind=Action%7CButton&selectedStory=Colors&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel
- `transition` doesn't work on `linear-gradient` values, but using a pseudo element this can be accomplished: https://keithjgrant.com/posts/2017/07/transitioning-gradients/
=> Resolve issue #231 by targeting specific CSS properties with transition-property

packages/matchbox-icons/src/icons/ErrorIcon.js, packages/matchbox-icons/src/index.js, unreleased.md
Resolves #220
**What's Changed**
Exports `Error` as `ErrorIcon`
**To Test**
http://localhost:9001/?selectedKind=Icons%7Cmatchbox-icons&selectedStory=all%20icons&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel
=> Resolve Issue #220 - Add ErrorIcon

cypress/integration/Select.spec.js, packages/matchbox/src/components/Select/Select.js, packages/matchbox/src/components/Select/tests/Select.test.js, packages/matchbox/src/components/Select/tests/__snapshots__/Select.test.js.snap
Resolves #256 
Adds `id` to the `<select>` element directly instead of on the label only to properly associate the `<label>` and the form control.
- On `master`, go to: http://localhost:9001/?selectedKind=Form%7CSelect&selectedStory=With%20help%20text&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel and click on the select label - note that the select does not receive focus - this indicates a broken label/form control association
- On this branch, do the same and notice that focus is handled properly
=> Resolve issue #256 by adding id attribute to select element

packages/matchbox/src/components/Tag/Tag.module.scss
Resolves #251 
- Updated display of tag `.Content` from `inline-block` to `inline-flex`
- Added some horizontal spacing for child SVG elements
**Before:**
**After:**
Look at variants of `<Tag/>` and verify vertical centering:
http://localhost:9001/?selectedKind=Feedback%7CTag&selectedStory=basic%20tag&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel
=> Resolve Issue #251 - Update Tag component styles to vertically center content

packages/matchbox/src/components/Pager/Next.js, packages/matchbox/src/components/Pager/Previous.js, packages/matchbox/src/components/Pager/tests/__snapshots__/Next.test.js.snap, packages/matchbox/src/components/Pager/tests/__snapshots__/Previous.test.js.snap
Resolves #219 
* `<ScreenReaderOnly>` component incorporated in to `<Next>` and `<Previous>` components
* Tests updated to reflect changes
* Verify that content is present within the DOM, but is not visually present
=> Resolve Issue #219 Incorporate ScreenReaderOnly component in to Next and Previous Pager components and relevant snapshots

packages/matchbox/src/components/Snackbar/Snackbar.js, packages/matchbox/src/components/Snackbar/Snackbar.module.scss, packages/matchbox/src/components/Snackbar/tests/Snackbar.test.js, packages/matchbox/src/components/Snackbar/tests/__snapshots__/Snackbar.test.js.snap, unreleased.md
* Incorporated icons that communicate the Snackbar component instance status in addition to the instance's color
* Incorporated labels for these icons so that screen readers can also interpret the Snackbar status
* Screenshots:
1. Visit the [Snackbar Story](http://localhost:9001/?selectedKind=Feedback%7CSnackbar&selectedStory=Default&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel)
1. Check that components render with relevant `aria-label` HTML attributes
1. Check that each status of Snackbar component renders a distinct icon
=> Resolve Issue #234 by incorporating icons in to the Snackbar component

config/helpers.js, package-lock.json, package.json, packages/matchbox-icons/package-lock.json, packages/matchbox/package.json, packages/matchbox/src/components/Text/Text.js, packages/matchbox/src/components/Text/index.js, packages/matchbox/src/components/Text/styles.js, packages/matchbox/src/components/Text/tests/Text.test.js, packages/matchbox/src/components/Text/tests/__snapshots__/Text.test.js.snap, packages/matchbox/src/components/ThemeProvider/tests/ThemeProvider.test.js, packages/matchbox/src/components/ThemeProvider/tests/__snapshots__/ThemeProvider.test.js.snap, packages/matchbox/src/components/index.js, stories/Text.stories.js, unreleased.md
- Adds a new primitive `<Text />` component.
- Like the `<Box />`, this component makes use of styled-system, and has the options to adjust `color`, `space`, and `typography` system props.
- Start storybook with `npm run start:storybook`
- Visit http://localhost:9001/?path=/story/text--styled, and other stories.
- Verify the available props work, or provide feedback on the API.
<details>
<summary>Screenshots</summary>
</details>
<details>
<summary>PR Checklist</summary>
</details>
=> Add primitive Text component

.eslintrc, packages/matchbox/src/components/UnstyledLink/UnstyledLink.js, packages/matchbox/src/helpers/propTypes.js, stories/navigation/UnstyledLink.stories.js, unreleased.md
- Adds a custom prop type wrapper called `deprecate` to provide end users with a warning message
- Makes use of `deprecate` on an already deprecated prop in `UnstyledLink`
- React's `prop-types` warning return an `Error`, this function returns a console warning. I'm not entirely sure of FB's reasoning here, or if I should use `Error` instead
- Verify the `Component` prop on `UnstyledLink` emits a console warning
=> Custom Deprecate Prop Type

cypress/integration/Modal.spec.js, packages/matchbox/src/components/Modal/Content.js, packages/matchbox/src/components/Modal/Modal.js, packages/matchbox/src/components/Modal/tests/__snapshots__/Modal.test.js.snap, stories/overlays/Modal.stories.js, unreleased.md
Resolves #281
- Replaces instances of `data-test` with `data-id`
- Tests that leverage these attributes continue to pass
- No instances of `data-test` remain in components
=> Resolve #281 - Replace data-test with data-id

packages/matchbox/src/components/Tag/Tag.module.scss, unreleased.md
Resolves #283 
- Fixes vertical alignment on the Tag close button
- Go to the Tag story: http://localhost:9001/?selectedKind=Feedback%7CTag&selectedStory=with%20remove%20action&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel
- Verify the close buttons align with tag content
-  Provide screenshots or [screen recordings](https://getkap.co/) for any visual changes.
-  Get approval from a UX team member (**#uxfe** or **#design-guild** on Slack) for any visual changes.
=> Resolve 283 - Fix vertical alignment of tag close button

packages/matchbox/src/components/Slider/Slider.js, packages/matchbox/src/components/Slider/tests/Slider.test.js, stories/form/Slider.stories.js, unreleased.md
- Resolves #295 - Fixes a bug math in the slider handle position calculation when `min` is a positive number
- Resolves #296 - Slider passes through `aria-controls`
- Visit http://localhost:9001/?selectedKind=Form%7CSlider&selectedStory=basic%20slider&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel
- Interact with the first slider:
```js
<Slider min={100000} max={1000000}/>
```
=> Issues 295 & 296 - Fix track rendering with positive min values & pass through aria-controls

packages/matchbox/package.json, unreleased.md
- `matchbox-icons` is now listed as a peer dependency in `matchbox` to reduce bundle size
(After publishing)
- Install `matchbox` in an app, and verify icons are not bundled with the components
- Can use https://marketplace.visualstudio.com/items?itemName=wix.vscode-import-cost
- Or verify npm warns of a peer dependency when installing, while icons are uninstalled
=> FE-796 List matchbox-icons as a peer dependency

cypress/integration/Toggle.spec.js, stories/action/Toggle.stories.js
FE-773 - Toggle component Cypress tests
Adds Cypress testing to the matchbox toggle component.
Run storybook locally -> `npm run start:storybook`
Run the e2e tests -> `npm run test:e2e:gui`
=> FE-773 - Toggle component (cypress tests)

cypress/integration/Pagination.spec.js
Small follow up to FE-776
- Scopes Pagination's Cypress tests to avoid picking up on Storybook addons
- Start storybook and run e2e tests
- `npm run start:storybook` and `test:e2e:headless`
- NA
=> Scope pagination to container to skip storybook addons

cypress/integration/Tooltip.spec.js, packages/matchbox/src/components/Tooltip/Tooltip.module.scss, unreleased.md
Added cypress tests for the tooltip component.
Run storybook locally -> `npm run start:storybook`
Run the e2e tests -> `npm run test:e2e:gui`
=> FE-778 - Add cypress tests for the tooltip component 

packages/design-tokens/formats/meta.js.js, packages/design-tokens/formats/utils.js, packages/design-tokens/gulpfile.js/index.js, packages/design-tokens/package-lock.json, packages/design-tokens/package.json, packages/design-tokens/tokens.scss, packages/design-tokens/tokens/index.yml, packages/design-tokens/tokens/motion-duration.yml, packages/design-tokens/tokens/motion-ease.yml, packages/matchbox/package-lock.json, packages/matchbox/package.json
Adds the following transition property tokens:
- duration
- motion-duration-fast: 0.15s
- motion-duration-medium: 0.3s
- motion-duration-slow: 0.7s
- easing
- motion-ease-in: cubic-bezier(.35, 0, .7, .2)
- motion-ease-out: cubic-bezier(0, 0, .3, 1)
- motion-ease-inout: cubic-bezier(.4, 0, .3, 1)
- Run the token build locally from within design-tokens with `npm run build`
- Inspect the built assets in `dist` to verify the two sets of tokens
=> FE-852 Add Motion Tokens

packages/matchbox/src/components/Tag/Tag.js, packages/matchbox/src/components/Tag/styles.js, packages/matchbox/src/components/Tag/tests/Tag.test.js, stories/feedback/Tag.stories.js, unreleased.md
For the Tag component: 
Renamed the "gray" variant to "darkGray", added a "lightGray" variant and made that the default.
Verify the default Tag has background color `color_gray_100` with `color_gray_400` border.
Verify the "lightGray" Tag has background color `color_gray_100` with `color_gray_400` border.
Verify the "darkGray" Tag has background color `color_gray_300` with `color_gray_500` border.
=> FE-906 Add lightGray Tag variant and rename gray to darkGray

packages/matchbox/src/components/Banner/Banner.js
- Restricts the link color override in Banners to only children and not Banner buttons
- Visit banner stories, add a `to` prop to one of the banner actions. EG:
```js
<Banner
action={{
content: 'test',
to: 'test',
external: true
}}
>
```
=> FE-916 Fix Banner buttons as links

packages/matchbox/src/components/ComboBox/ComboBoxTextField.js, packages/matchbox/src/components/ComboBox/ComboBoxTextField.module.scss, packages/matchbox/src/components/ComboBox/tests/__snapshots__/ComboBoxTextField.test.js.snap, packages/matchbox/src/components/Tag/Tag.module.scss, unreleased.md
This is follow-up to #284 
- Wrapped ComboBoxTextField items with `<div />`'s to control the spacing
- Make sure to change the with of the available space to test wrapping
=> FE-921 Tag contents and close button are not vertically aligned

packages/matchbox/src/components/Snackbar/styles.js, stories/feedback/Snackbar.stories.js, unreleased.md
Added link styles for the status styled component.
Load up the snackbar in storybook and verify the links I put in are the correct color per status. (Links should also be underlined)
=> FE-918 - Fix active styled-component link styles (Snackbar Links)

packages/matchbox/src/components/Banner/Banner.js, packages/matchbox/src/components/Banner/styles.js, packages/matchbox/src/components/Expandable/Expandable.js, packages/matchbox/src/components/Expandable/styles.js, packages/matchbox/src/components/Expandable/tests/Expandable.test.js, packages/matchbox/src/components/Snackbar/Snackbar.js, packages/matchbox/src/components/Snackbar/styles.js, packages/matchbox/src/components/Tag/Tag.js, unreleased.md
- Specifies `type="button"` on component buttons in Snackbar, Banner, Expandable, Tag
- Also changes the expandable arrow rotations to match mockups
- Verify these component buttons have type specified
- Optional, use one of these components in an HTML form and verify they do not submit the form. Try wrapping expandable with `<form onSubmit={() => alert('submit')}>` in a story.
- Try with Safari, I couldn't reproduce with Chrome
=> FE-926 Specify Button Type

packages/matchbox/src/components/Table/TableElements.js, packages/matchbox/src/components/Table/styles.js, unreleased.md
- Fixes spacing issues between cells (not sure how/when this got introduced)
- Scopes table row styles to `thead` and `tbody`
- Removes the `header`, was added in the Table restyling PR but can be removed now
- Verify there are no visual bugs on the Table stories
=> FE-944 Fix Table.Row styling

packages/matchbox/src/components/Tabs/Tabs.js, packages/matchbox/src/components/Tabs/styles.js, packages/matchbox/src/components/Tabs/tests/Tabs.test.js, stories/navigation/Tabs.stories.js, unreleased.md
- Prevents tab text from wrapping for tabs with multiple words
- Specifies button `type` to prevent forms from submitting when clicking tabs
- Fixes instances where `component` or `Component` pass through a link
- Visit tab stories, verify text does not wrap
- Optionally, you can wrap tabs in a `form` with an onSubmit to check if clicking a tab submits the form
=> FE-950 & FE-983 – Prevent tab content from wrapping, Specify tab button type, Fix component wrappers

packages/matchbox/src/components/Label/Label.js, packages/matchbox/src/components/Label/tests/Label.test.js, packages/matchbox/src/components/Select/Select.js, unreleased.md
[FE-942](https://jira.int.messagesystems.com/browse/FE-942)
- `<Label/>` renders as `null` when no `"label"` is passed in
- Verify no `<Label/>` renders for the `<TextField/>` or `<Select/>` when no `"label"` is provided.
=> FE-942 - <Label/> component does not render when no "label" prop is provided

cypress/integration/Slider.spec.js, packages/matchbox/src/components/Tooltip/Tooltip.js, packages/matchbox/src/components/Tooltip/TooltipOverlay.js, packages/matchbox/src/components/Tooltip/tests/Tooltip.test.js, stories/overlays/Tooltip.stories.js, unreleased.md
- Duplicates tooltip content into a screen reader only element next to triggers
- Adds a new `as` prop to Tooltips, defaults to `span` – Realized the old implementation forced an inline-block `span`, so this should not be a breaking change
- Tooltips now visible if trigger is focused
- Verify Tooltip stories and that tooltips are positioned correctly
=> FE-981 Fix Tooltip positioning

packages/matchbox/src/components/Button/styles.js, unreleased.md
[FE-986](https://jira.int.messagesystems.com/browse/FE-986)
- Adds `cursor: pointer;` to the `<Button/>` component styles
- Replaces transition value with design token
- Hover over a button and check out the cursor - should be a pointer!
- Make sure CSS transitions are still working
=> FE-986 - Adds appropriate cursor style for the Button component

packages/matchbox/src/components/TextField/TextField.js, unreleased.md
[FE-982](https://jira.int.messagesystems.com/browse/FE-982)
- Properly pass height prop to styled component that was set statically
- Run Storybook locally and go here: `/iframe.html?id=form-textfield--multiline`
- Verify that on the `rc/4.0.0` and go to the above URL, verify the bug. Checkout `FE-982` and verify the bug is fixed.
=> FE-982 - Properly pass height to styled component

packages/matchbox/src/components/TextField/TextField.js
- Sets line height on multiline text fields – previously they were set to 2.5rem
- Visit textfield stories and verify height of the inputs are correct
- Visit textfield multiline story and verify the line height of the textarea is correct
=> FE-992 Set lineheight and padding-y for multiline textfields

.storybook/preview-head.html, .storybook/preview.js, packages/matchbox/src/components/ThemeProvider/ThemeProvider.js, packages/matchbox/src/components/ThemeProvider/tests/ThemeProvider.test.js, unreleased.md
- Adds a new `target` prop to `ThemeProvider`, see https://styled-components.com/docs/api#stylesheetmanager
- Testing this in storybook is difficult due to our setup, you will need to remove all but one story and make sure only a single story uses `addDecorator`. (We have a follow up ticket to clean up stories)
- In a single `addDecorator` add:
```js
addDecorator(storyFn => (
<ThemeProvider target={document.getElementById('styles-target')}>
{storyFn()}
</ThemeProvider>
));
```
- Verify the story works
=> FE-1018 Support CSS injection DOM node targeting

packages/matchbox/src/components/Stack/Stack.js, packages/matchbox/src/components/Stack/tests/Stack.test.js, unreleased.md
- One-liner to fix this bug
- Removed use of `.not.toHaveStyleRule` in Stack tests because it was not working
- Replaced `wrapper.find('div').at(0)` with `wrapper.find('#child-1').parent()`
- Added an example to tests
~- [ ] Provide screenshots or [screen recordings](https://getkap.co/) for any visual changes.~
~- [ ] Get approval from a UX team member (**#uxfe** or **#design-guild** on Slack) for any visual changes.~
=> FE-1068: Last item in Stack has bottom margin

cypress/integration/Tab.spec.js, packages/matchbox/src/components/Tabs/Tabs.js, packages/matchbox/src/components/Tabs/styles.js, stories/navigation/Tabs.stories.js, stories/storyHelpers/StoryContainer.js, unreleased.md
-  `Tabs` are now responsive for both fitted and non-fitted variations
-  `Tab` now uses a `pointer` cursor on hover
-  `Tabs` now accept the `borderBottom` system prop
-  Follow up ticket for keyboard navigation: FE-1067
- Visit Tab stories, verify responsive behavior
=> FE-996 Tab Updates

packages/matchbox/src/components/Page/Page.js, stories/layout/Page.stories.js
- Reorder Primary and Secondary actions on smaller screens
- If only one secondary action, display in a button
- Remove aria-describedby
=> UX-157 Page Component Updates

packages/matchbox/src/components/Checkbox/Group.js, packages/matchbox/src/components/Checkbox/tests/Group.test.js, packages/matchbox/src/components/HelpText/HelpText.js, packages/matchbox/src/components/Label/Label.js, packages/matchbox/src/components/Radio/Group.js, packages/matchbox/src/components/Radio/tests/Group.test.js, unreleased.md
- Use Label component to match styles to TextField label
- Stack around group checkboxes and radio groups
- indent helptext
=> UX-158 Update Radio and Checkbox Components

packages/matchbox/src/components/Table/Table.js, packages/matchbox/src/components/Table/styles.js, packages/matchbox/src/components/Table/tests/Table.test.js, stories/layout/Table.stories.js, unreleased.md
- Tables now have a `freezeFirstColumn` boolean prop
- Tables are now responsive
- run storybook `npm run start:storybook`
- visit the table stories and verify responsiveness works
=> UX-213 Allow tables to freeze one column

cypress/integration/Button.spec.js, packages/matchbox/src/components/Button/Button.js, packages/matchbox/src/components/Button/styles.js, packages/matchbox/src/components/Button/tests/Button.test.js, packages/matchbox/src/components/Button/tests/__snapshots__/utils.test.js.snap, packages/matchbox/src/components/Pager/tests/Next.test.js, packages/matchbox/src/components/Pager/tests/Previous.test.js, packages/matchbox/src/components/Spinner/Spinner.js, packages/matchbox/src/components/Spinner/styles.js, packages/matchbox/src/components/Spinner/tests/Spinner.test.js, stories/action/Button.stories.js, stories/feedback/Spinner.stories.js, unreleased.md
- Adds new prop `loading` to buttons
- Run storybook and visit the two loading stories. One of them allows you to toggle on/off
=> UX-215 Add button loading states

codecov.yml, cypress/integration/Tab.spec.js, packages/matchbox/src/components/Popover/PopoverContent.js, packages/matchbox/src/components/Tabs/Tab.js, packages/matchbox/src/components/Tabs/Tabs.js, packages/matchbox/src/components/Tabs/readme.md, packages/matchbox/src/components/Tabs/styles.js, packages/matchbox/src/components/Tabs/tests/Tabs.test.js, packages/matchbox/src/components/Tabs/useTabConstructor.js, packages/matchbox/src/components/Text/Text.js, packages/matchbox/src/components/UnstyledLink/UnstyledLink.js, packages/matchbox/src/helpers/keyEvents.js, packages/matchbox/src/hooks/index.js, packages/matchbox/src/hooks/useTabs.js, stories/Text.stories.js, stories/navigation/Tabs.stories.js, unreleased.md
- Adds support for tab keyboard navigation
- Adds new prop `keyboardActivation` defaults to `auto`
- Adds new `useTabs` hook to support tab state implementation
- Refs can now be forwarded to `Text`, `UnstyledLink`
- Tabs with custom components now require a `ref` to be forwarded
Key | Desc
-- | --
Enter / Spacebar | Activates focused tab – inherited through button and anchor tags with href
Tab | When focus is before tablist moves focus to the active tab. If focus is on the active tab moves focus to the next element in the keyboard focus order, and skip the next tab.
ArrowLeft / ArrowRight | Navigates between tabs when orientation is "horizontal". When on last, should move to first. When on first, should move to last.
Home / PageUp | Navigates to the last tab in the TabList. …
=> UX-155 Add Tab keyboard navigation

packages/matchbox/src/components/Button/styles.js, packages/matchbox/src/components/ComboBox/styles.js, packages/matchbox/src/components/Select/Select.js, packages/matchbox/src/components/Select/tests/Select.test.js, packages/matchbox/src/components/TextField/TextField.js, packages/matchbox/src/components/TextField/tests/TextField.test.js, packages/matchbox/src/styles/helpers.js, unreleased.md
- Adds focus styles to `TextField` `Select` and `ComboBoxTextfield`
- Visit related stories and test focus
=> UX-240 Add focus styles to textfield, combobox, select

packages/matchbox/src/components/ComboBox/tests/ComboBoxTextField.test.js, packages/matchbox/src/components/Tag/Tag.js, packages/matchbox/src/components/Tag/tests/Tag.test.js
Closes #502 
- Changes tag screen reader only text from 'Close' to 'Remove'
Run storybook and verify the Tag remove buttons have 'Remove'
=> Resolve #502 - Changes tag screen reader text to 'Remove'

.gitignore, CHANGELOG.md, README.md, scripts/changelog.sh, site/gatsby-config.js
- Removes the auto `mdx` generation from the `changelog` script.
**New Workflow:**
- Before first release, set up your github auth token in `.env`
- Merge all pull requests you wish to release to `main`
- Run `npm run changelog`
- Edit `CHANGELOG.md` with correct version number of your release
- Run `lerna version`
- Run `lerna publish`
- Run `npm run changelog`
- Run git status, or check `CHANGELOG.md`
- You should see unreleased PR info
=> Update changelog scripts to prepend to root file

packages/matchbox/src/components/Panel/Section.js, packages/matchbox/src/components/Panel/tests/Panel.test.js, stories/layout/Panel.stories.js
Closes #529 
- Passes `className` to `Panel.Section`
- Run storybook and visit the Panel story with multiple sections
- Verify the className is in the DOM
=> Resolve #529 - className is now accepted by Panel.Section

packages/matchbox/src/components/DatePicker/Day.js, packages/matchbox/src/components/DatePicker/styles.js, packages/matchbox/src/components/DatePicker/tests/DatePicker.test.js, stories/form/DatePicker.stories.js
- Adds `pointer-events none` to disabled days
- Prevents days from rendering if they are outside
- Run storybook and visit the datepicker stories
- Try clicking on days outside the month or disabled days
- Should not see a console.log
=> UX-275 Removes datepicker's outside and disabled days click events

packages/matchbox/src/components/Page/Page.js, packages/matchbox/src/components/Popover/Popover.js, packages/matchbox/src/components/Popover/PopoverContent.js, packages/matchbox/src/components/Popover/styles.js
Closes #517 
- Page secondary action buttons use `outlineBorder` now and render as a square correctly
- Adjusted the Page breakpoints so the actions dont collapse so soon
- The `left` prop on Popover now supports responsive arrays
- Visit Page stories and verify the right button style is used and the kebab is centered with multiple secondary actions
- Test responsive behavior
=> Resolve #517 - Page secondary actions now render correctly, Adjust Page responsive behavior

packages/matchbox/package-lock.json, packages/matchbox/package.json, packages/matchbox/rollup/config.js, packages/matchbox/src/hooks/index.js, packages/matchbox/src/hooks/tests/useCopyToClipboard.test.js, packages/matchbox/src/hooks/useCopyToClipboard.js, stories/utility/useCopyToClipboard.stories.js
- Adds new `useCopyToClipboard` hook
Usage:
```js
const { copy, copied } = useCopyToClipboard({ timeout: 2000 });
<Button onClick={() => copy('string')}>
{copied ? 'String has been copied' : 'Copy to clipboard'}
</Button>
```
- Run storybook and visit the copy to clipboard story
- Verify a string is copied when clicking the button
=> UX-247 Add useCopyToClipboard hook

packages/matchbox/src/components/Modal/Modal.js
- Fixes this bug:
- Run storybook and visit modal toggle demo
- Verify modal panel expands to the max width of its container
=> UX-278 Modal content now expands to its container

packages/matchbox/src/components/Column/Column.js, packages/matchbox/src/components/Columns/Columns.js, stories/layout/Columns.stories.js
Closes #551 
- Adds `padding-top` to `Columns` if they are `collapsed` - first child has its padding negated
- Visit the Columns stories that collapse columns
- Verify there is vertical space between them
=> Resolves #551 - Adds correct vertical margin between collapsed columns

packages/matchbox/src/components/UnstyledLink/UnstyledLink.js, packages/matchbox/src/components/UnstyledLink/tests/UnstyledLink.test.js
Closes #540 
- Passes `role` to all UnstyledLink variations
- Ensure unit tests pass
=> Resolves #540 - Pass through role to UnstyledLinks with wrappers or to links

packages/matchbox/src/components/Table/Table.js, packages/matchbox/src/components/Table/TableElements.js, packages/matchbox/src/components/Table/styles.js, stories/layout/Table.stories.js
=> UX-283 & UX-285 Add new alignY prop to Table.Row & Fix element overflow on Table

packages/matchbox/src/components/Drawer/Drawer.js
- Focus is now placed on the Drawer container when it is opened
- Run storybook, visit http://localhost:9001/iframe.html?id=overlays-drawer--drawer-example
- **Focus lock does not work if its in an iframe - use this link**
- Verify the container is focused on open, you can try removing `tabIndex='-1'` to make focus outline visible
=> UX-281 Focus on Drawer container on open

packages/matchbox/src/components/ComboBox/styles.js, packages/matchbox/src/components/Select/Select.js, packages/matchbox/src/components/TextField/TextField.js, packages/matchbox/src/index.js, packages/matchbox/src/styles/helpers.js, packages/matchbox/src/styles/index.js, stories/utility/Styles.stories.js
- Ticket notes only to export the focusOutline helper, but thought it would be a good idea to export all of them
- There are some changes included with the `modifier` parameter, these were initially made in #554 and are merged into rc/4.1.0. This just promotes it up to 4.0.x.
- Exports all styled-component helpers, under a `styles` object
- Visit the stories under Utility/StyleHelpers
=> UX-279 Export all styled-component helpers

packages/matchbox/src/components/Column/Column.js, packages/matchbox/src/components/Columns/Columns.js, packages/matchbox/src/components/Layout/Layout.js, packages/matchbox/src/components/Layout/Section.js, packages/matchbox/src/components/Layout/SectionTitle.js, packages/matchbox/src/components/Layout/index.js, packages/matchbox/src/components/Layout/tests/Layout.test.js, packages/matchbox/src/components/Layout/tests/Section.test.js, packages/matchbox/src/components/Layout/tests/SectionTitle.test.js, packages/matchbox/src/components/index.js, stories/layout/Layout.stories.js
New Layout Component
- Added `Layout` Component
- Added `Layout.Section` Component
- `Layout.Section` accepts `variant` prop with options `oneColumn, twoColumn, leftAnnotated, rightAnnotated`
-  Verify Layout story in storybook
=> UX-270 Create Layout Component

config/helpers.js, packages/matchbox/src/components/Banner/tests/Banner.test.js, packages/matchbox/src/components/Button/styles.js, packages/matchbox/src/components/Button/tests/Button.test.js, packages/matchbox/src/components/Pagination/tests/Pagination.test.js, packages/matchbox/src/components/ThemeProvider/theme.js, packages/matchbox/src/components/Tooltip/tests/Tooltip.test.js, stories/action/Button.stories.js
- Darkens background hover colors for `outline` `outlineBorder` and `flat` buttons
- Run storybook and visit the button color story
=> UX-284 Darken button hover background colors

.playroom/snippets.js, packages/matchbox/src/components/Button/Button.js, packages/matchbox/src/components/Button/styles.js, packages/matchbox/src/components/DatePicker/Navbar.js, packages/matchbox/src/components/Drawer/Header.js, packages/matchbox/src/components/Page/Page.js, packages/matchbox/src/components/Pagination/Pagination.js, packages/matchbox/src/components/Tabs/Tabs.js, stories/action/Button.stories.js
- Adds a new `variant` prop to `Button`
- Deprecates the old props `outline` `outlineBorder` `flat`
- Updates the components, and playroom snippets, that used the old props
- Will update the site in another ticket
- Run storybook and visit - http://localhost:9001/?path=/story/action-button--variants
- Check http://localhost:9001/?path=/story/action-button--deprecated-variants still works
=> UX-263 Adds Button variant prop

packages/matchbox/src/components/Button/Button.js, packages/matchbox/src/components/Button/Icon.js, packages/matchbox/src/components/Button/tests/Button.test.js, stories/action/Button.stories.js
Closes #522 
- Adds new `Button.Icon` component to handle vertically centering icons easily inside buttons
- Run storybook and visit http://localhost:9001/?path=/story/action-button--icon
=> UX-292 Add Button.Icon

packages/matchbox/src/components/ThemeProvider/globalStyles.js
- Un-nests the hover styles in global CSS
- Bug is not reproducible through storybook or playroom, I published a test version at `4.0.14-beta.0`
- Compare these two versions of matchbox:
- Hover - https://codesandbox.io/s/wonderful-euler-xzdue
- No hover - https://codesandbox.io/s/little-meadow-6is53
(Edit: updated the links)
=> UX-291 Fix global anchor tag hover styles

packages/matchbox/src/components/CodeBlock/styles.js, stories/utility/CodeBlock.stories.js
Resolves #582 
- Adds a missing semicolon to the `<CodeBlock />` component styles
- Updates Storybook story name to match formatting
- Start Storybook and go to `/?path=/story/utility-codeblock--chevrons` to verify the background color renders correctly
- [X ] Add the correct `type` label
=> Resolves #582 - Adds missing semicolon to CodeBlock component styles

packages/matchbox/src/components/ActionList/Action.js, packages/matchbox/src/components/ActionList/ActionList.js, packages/matchbox/src/components/ActionList/Section.js, packages/matchbox/src/components/ActionList/tests/ActionList.test.js, packages/matchbox/src/components/ComboBox/ComboBoxMenu.js, packages/matchbox/src/components/Page/Page.js, packages/matchbox/src/components/Tabs/Tabs.js, stories/action/ActionList.stories.js
- Adds `ActionList.Action` and `ActionList.Section` components
- Updates components that use `ActionList`
- Verify old usage still works here: http://localhost:9001/?path=/story/action-actionlist--deprecated-usage
- Verify new usage works: http://localhost:9001/?path=/story/action-actionlist--within-popovers
=> UX-224 Support composable ActionList components

packages/matchbox/src/components/Checkbox/Checkbox.js, packages/matchbox/src/components/Checkbox/styles.js, packages/matchbox/src/components/Checkbox/tests/Checkbox.test.js, stories/form/Checkbox.stories.js
- Adds support for `indeterminate` checked state
- Specifies `defaultChecked` prop doesn't work with intermediate, input must be fully controlled
- Run storybook and visit http://localhost:9001/?path=/story/form-checkbox--indeterminate-group
=> UX-286 Add indeterminate checkbox support

packages/matchbox/src/components/RadioCard/Group.js, packages/matchbox/src/components/RadioCard/tests/RadioCard.test.js, stories/form/RadioCard.stories.js
- Removes the `RadioCard.Group` disabled prop - It didn't match the `Radio` components `disabled` behavior
- Fixes a bug where the `Group`s `disabled` prop was overwriting the children's
- Visit: http://localhost:9001/?path=/story/form-radiocard--disabled-radio
- Verify the first two radio cards are disabled
=> UX-318 Remove RadioCard.Group disabled prop

packages/matchbox/src/components/ActionList/ActionList.js, packages/matchbox/src/helpers/array.js, packages/matchbox/src/helpers/tests/array.test.js
- Allows the `filterByVisible` function to fail gracefully by returning an empty array
- Visit page stories: http://localhost:9001/?path=/story/layout-page--basic-example
- Try to add `null` or `undefined` into `secondaryActions`
- Do the same with actions here: http://localhost:9001/?path=/story/action-actionlist--deprecated-usage
=> UX-324 Page and Actionlist actions render with null actions

site/src/pages/index.mdx
Resolves #618 
- `cd site && npm start`
- Verify the link goes to the correct page
=> Resolves #618 - Fixes incorrect link to Matchbox Storybook site

packages/matchbox/src/components/Button/Icon.js
- Added margin prop to Button.Icon
- verify Button Icon story
=> UX-323 Add margin prop to Button.Icon

packages/matchbox/src/components/Modal/Content.js
Closes #617 
- Sets Modal.Content `overflowY` to `auto` instead of `scroll`
- this allows short modals to hide the scrollbar
- Visit: http://localhost:9001/?path=/story/overlays-modal--toggle-example
- Verify no scrollbar is visible when OS system preference are set to 'Always show scrollbars'
- Also verify the Tall modal example is still scrollable
=> Issue 617 Set Modal.Content overflow-y to auto

packages/matchbox/src/components/ThemeProvider/theme.js, site/src/components/SystemProps/data.js, site/src/pages/components/system-props.mdx
Closes #608 
- Adds `motion` tokens to the styled-system theme file
- Updates the site documentation to include both motion and zindices
- Verify motion is included in the theme by accessing `props.theme` from any component under `ThemeProvider`
=> Issue-608 Add motion to theme

packages/matchbox/src/components/Column/Column.js, packages/matchbox/src/components/Column/tests/Column.test.js
Resolves #625 
- `className` accepted as a prop for the `<Column/>` component
- On the Storybook site, try:
```js
<Box as={Column} display="none">I am invisible!</Box>
```
=> Resolves #625 - Add support for the className prop for the Column component

packages/matchbox/src/components/Checkbox/Checkbox.js, packages/matchbox/src/components/Checkbox/tests/Checkbox.test.js, packages/matchbox/src/components/Radio/Radio.js, packages/matchbox/src/components/Radio/tests/Radio.test.js, packages/matchbox/src/components/Select/Select.js, packages/matchbox/src/components/Select/tests/Select.test.js, packages/matchbox/src/components/TextField/TextField.js, packages/matchbox/src/components/TextField/tests/TextField.test.js
Resolves #630 
- Adds `React.forwardRef` to `Radio` `Checkbox` `Textfield` and `Select` to allow refs to pass through.
- Run storybook, and verify refs can be passed through
=> Issue 630 - Forward refs to Radio, Checkbox, Textfield and Select

packages/matchbox/src/components/Select/styles.js
- Updates Select text styles to match Button
- Verify Select stories
=> UX-329 match Select text styles to Button

packages/matchbox/src/components/Modal/Content.js, site/src/pages/components/modal.mdx, stories/overlays/Modal.stories.js
- Adds `padding` system prop to `Modal.Content`
- Verify `Modal` stories - added new system props story
=> UX-336 Add Padding system prop to Modal.Content

cypress/integration/RadioCard.spec.js, packages/matchbox/src/components/RadioCard/Group.js, packages/matchbox/src/components/RadioCard/RadioCard.js, packages/matchbox/src/components/RadioCard/tests/RadioCard.test.js, site/src/pages/components/radiocard.mdx, stories/form/RadioCard.stories.js
Closes #629 
- Adds new `grid` orientation option
- Removes restriction on React children inside radio card groups
=> UX-334 Support grid orientation & Allow non RadioCard children

packages/matchbox/src/components/Modal/Content.js, stories/overlays/Modal.stories.js
- Removes modal content default prop `p`
- Hardcodes the default instead so `padding` works when passed to the component
- Visit the modal story: http://localhost:9001/?path=/story/overlays-modal--system-props
- Verify `p` works as well as `padding`
=> UX-342 Support  prop on Modal.Content

packages/matchbox/src/components/Picture/Picture.js, packages/matchbox/src/components/Picture/index.js, packages/matchbox/src/components/Picture/tests/Picture.test.js, packages/matchbox/src/components/index.js, stories/media/Picture.stories.js
- Adds new `Picture` and `Picture.Image` components
- Visit: http://localhost:9001/?path=/story/media-picture--basic-image
=> UX-223 Add Picture Component

cypress/integration/ListBox.spec.js, packages/matchbox/src/components/ListBox/ListBox.js, packages/matchbox/src/components/ListBox/Option.js, packages/matchbox/src/components/ListBox/useOptionConstructor.js, stories/form/ListBox.stories.js
- Properly tabs through the ListBox - bypassing options
- Opens the Listbox when focused and pressing arrow up or down
- Returns focus to the Button when closed
- Visit http://localhost:9001/?path=/story/form-listbox--with-a-ref
- Verify keyboard interactions
=> UX-345 Support additional ListBox keyboard interactions

packages/matchbox/src/components/ComboBox/ComboBoxTextField.js, packages/matchbox/src/components/ComboBox/tests/ComboBoxTextField.test.js, site/src/pages/components/combobox.mdx, stories/form/ComboBox.stories.js
- Adds `delimiter` string prop to the combobox textfield
- Visit http://localhost:9001/?path=/story/form-combobox--with-delimiter
- Verify delimiter works
=> UX-335 Add ComboBoxTextField delimiter prop

packages/matchbox/src/components/Tabs/Tabs.js
- Listen for resize on Tabs component and not window
- Verify resize events are working on Tabs stories
=> UX-234 Tabs should measure overflow on component resize

packages/matchbox/src/components/Expandable/Expandable.js, packages/matchbox/src/components/Expandable/styles.js, packages/matchbox/src/components/Expandable/tests/Expandable.test.js, packages/matchbox/src/components/Panel/Section.js, stories/layout/Expandable.stories.js
- Fixes `padding` bug on Panel.Sections
- Adds `variant` prop to `Expandable` and a `borderless` variant
- Visit: http://localhost:9001/?path=/story/layout-expandable--borderless
- Visit panel stories and verify both `p` and `padding` can be set on panel sections
=> UX-350 Add borderless Expandable variant

cypress/integration/Modal.spec.js, packages/matchbox/src/components/Modal/Modal.js
- Focuses on a modal content container when opening
- Visit http://localhost:9001/?path=/story/overlays-modal--toggle-example
- Verify focus is on the container when opening
=> UX-356 Focus modal panel when opening

packages/matchbox/src/components/Column/Column.js, packages/matchbox/src/components/Columns/Columns.js, packages/matchbox/src/components/Columns/tests/Columns.test.js, packages/matchbox/src/components/Grid/tests/Column.test.js, packages/matchbox/src/components/Inline/Inline.js, packages/matchbox/src/components/Inline/tests/Inline.test.js, packages/matchbox/src/components/Layout/Layout.js, packages/matchbox/src/components/Layout/Section.js, packages/matchbox/src/components/Layout/SectionTitle.js, packages/matchbox/src/components/Layout/tests/Layout.test.js, packages/matchbox/src/components/Layout/tests/Section.test.js, packages/matchbox/src/components/Layout/tests/SectionTitle.test.js, packages/matchbox/src/components/Stack/Stack.js, packages/matchbox/src/components/Stack/tests/Stack.test.js, packages/matchbox/src/components/Text/Text.js, packages/matchbox/src/components/Text/tests/Text.test.js
Resolves #661 
- Adds `data-id` to `Stack` `Inline` `Columns` `Column` `Layout`
- Run storybook, and add `data-id` as a prop to the components
=> Issue 661 Add data-id props to all layout components

packages/matchbox/src/components/Button/Button.js, packages/matchbox/src/components/Button/styles.js, stories/action/Button.stories.js
- Added `white` button color
- Verify button stories
=> UX-352 Add white button color

packages/matchbox/src/components/TextField/TextField.js
- Uses `useResizeObserver` to set `prefix` and `suffix` widths in TextField
- Run storybook and visit http://localhost:9001/?path=/story/form-textfield--prefix-and-suffix
- Verify the widths are set correctly and horizontal padding is added to the input
- Note: I could not reproduce the bug referred to in the ticket
=> UX-357 Use resize observer for suffix and prefix measurements

config/helpers.js, cypress/integration/Layout.spec.js, packages/matchbox/src/components/Columns/Columns.js, packages/matchbox/src/components/Columns/tests/Columns.test.js, packages/matchbox/src/components/EmptyState/EmptyState.js, packages/matchbox/src/components/EmptyState/Image.js, packages/matchbox/src/components/Layout/tests/Section.test.js, stories/layout/Layout.stories.js
- Updates EmptyState so images appear above the text on smaller screen sizes
- Refactors Columns to use `useBreakpoint` instead of listening to window size
- Visit http://localhost:9001/?path=/story/layout-empty-state--basic-empty-state
- Verify responsiveness
=> UX-362 Update responsive Empty States

packages/matchbox/src/components/LabelValue/LabelValue.js, packages/matchbox/src/components/LabelValue/tests/LabelValue.test.js, stories/layout/LabelValue.stories.js
- Updates `LabelValue` component to be composable
- Adds `LabelValue.Label` and `LabelValue.Value` components
- verify `LabelValue` stories
=> UX-365 Make LabelValue composable

packages/matchbox/src/components/ListBox/useOptionConstructor.js, site/gatsby-config.js, site/package.json
- Fixes a bug where using a number value on a `ListBox.Option` throws an error
- Adds `start:localMatchbox` script to the site to make testing matchbox changes in the design site easier
- Verify [ListBox stories](http://localhost:9001/?path=/story/form-listbox--basic-listbox)
=> UX-367 Fix ListBox key events bug

package-lock.json, packages/matchbox/src/components/UnstyledLink/UnstyledLink.js, stories/navigation/UnstyledLink.stories.js
- Adds `disabled` prop of type `bool` to `UnstyledLink`
- Adds CSS to signify that the `UnstyledLink` is disabled
- Fixes #700 
- Verify [UnstyledLink story](http://localhost:9001/?path=/story/navigation-unstyledlink--disabled)
=> UX-383 Add disabled prop and styles to UnstyledLink

packages/matchbox/src/components/Modal/Content.js, packages/matchbox/src/components/Modal/Modal.js, packages/matchbox/src/components/Modal/tests/Modal.test.js, stories/overlays/Modal.stories.js
- Adds a new prop on `Modal.Content` `restrictHeight`
- This new prop defaults to true, setting it to false allows Modals to expand to its contents height
- Visit http://localhost:9001/?path=/story/overlays-modal--tall-modal-without-height-restriction
- Visit http://localhost:9001/?path=/story/overlays-modal--tall-modal
- Verify behavior works as expected
=> UX-381 Make Modal.Content height restriction optional

packages/matchbox/src/components/UnstyledLink/UnstyledLink.js, packages/matchbox/src/components/UnstyledLink/tests/UnstyledLink.test.js, stories/navigation/UnstyledLink.stories.js
- Adds `aria-disabled` `tabindex` and an `onClick` handler when `UnstyledLink`s are `disabled`
- Visit http://localhost:9001/?path=/story/navigation-unstyledlink--disabled
- Verify links are not clickable or focusable
=> UX-401 Disable UnstyledLinks interaction when disabled

packages/matchbox/src/components/ActionList/Action.js, packages/matchbox/src/components/ActionList/styles.js, packages/matchbox/src/components/ActionList/tests/ActionList.test.js, site/src/pages/components/actionlist.mdx, site/src/pages/components/unstyledlink.mdx, stories/action/ActionList.stories.js
- Adds new `disabled` prop to Actionlist.Action
- Documents the new prop
- Also documents the new prop in UnstyledLink
- Run storybook and visit: http://localhost:9001/?path=/story/action-actionlist--as-buttons-and-checkboxes
- Verify the disabled button and link are not focusable or clickable
=> UX-400 - Handle disabled Actionlist Actions

packages/matchbox/src/components/ListBox/ListBox.js, packages/matchbox/src/components/ListBox/styles.js, stories/form/ListBox.stories.js
- Adds additional padding-right to the ListBox component
- Run storybook, visit the new ListBox story: http://localhost:9001/?path=/story/form-listbox--as-an-inline-element
=> UX-402 Fix Listbox padding as inline element

packages/matchbox/src/components/Modal/Footer.js, stories/overlays/Modal.stories.js
Closes #710 
- Modal.Footer buttons now use `variant` props instead of deprecated props
- Modal.Footer does not crash without children
- Modal.Footer now accepts non-Buttons as children, and renders them
- Run storybook and visit the new Modal stories:
- http://localhost:9001/?path=/story/overlays-modal--non-buttons
- http://localhost:9001/?path=/story/overlays-modal--empty-footer
=> UX-403 & Issue-710 Fix empty Modal.Footer & dynamic children

packages/matchbox/src/components/Tabs/Tabs.js, stories/navigation/Tabs.stories.js
- Listen for dynamic tab content changes and shift layout if they overflow 
- Verify the dynamic tabs story [here](http://localhost:9001/?path=/story/navigation-tabs--dynamic-tabs)
=> UX-407 - Force tab layout shift when tabs are dynamically updated

packages/design-tokens/tokens/sizing.yml, packages/matchbox/src/components/EmptyState/Image.js, packages/matchbox/src/components/ThemeProvider/theme.js
- Adds a new sizing token `1150` or 35rems
- Adds a max width to the Empty State image component
- Run storybook, and run the token build
- Visit: https://matchbox-storybook.netlify.app/iframe.html?id=layout-empty-state--basic-empty-state
- And Visit: http://localhost:9001/iframe.html?id=layout-empty-state--basic-empty-state
- Verify the size difference across different viewport sizes
=> UX-419 Reduce Empty State Image Size

packages/matchbox/src/components/Expandable/styles.js, packages/matchbox/src/styles/helpers.js, site/src/pages/components/mixins.mdx
Closes #706 
- Adds a radius option to the focusOutline helper
- Adds a focus outline to the Expandable button
- Run storybook and visit: http://localhost:9001/?path=/story/layout-expandable--with-image-title-and-subtitle
- Verify the Expandable toggle button has a visual outline
=> Resolves #706 Add noticable focus indicator on Expandable buttons

packages/matchbox/src/components/Banner/Banner.js, packages/matchbox/src/components/Banner/Media.js
- Fixes a bug that prevented the Banner dismiss button from being clicked on certain screen sizes
- Visit http://localhost:9001/?path=/story/feedback-banner--empty-banner-with-video
- Resize screen until video overlaps with the dismiss button
=> UX-420 Ensure Banner button is always on top of contents

packages/matchbox/src/components/Pagination/Pagination.js
- Closes #734 
- Removes deprecated Button prop usage from Pagination
- Run storybook and visit the pagination component stories
- Verify deprecated console warnings are not logged
=> issue-734 Remove deprecated Button props from Pagination component

packages/matchbox/src/components/EmptyState/Image.js, site/src/pages/components/emptystate.mdx, stories/layout/EmptyState.stories.js
- Makes EmptyState.Image maxWidth configurable as a system prop
- Visit the empty state stories, verify that the prop is configurable
=> UX-421 Make EmptyState.Image maxWidth configurable

packages/matchbox/src/components/EmptyState/Header.js, packages/matchbox/src/components/EmptyState/tests/EmptyState.test.js, stories/layout/EmptyState.stories.js
- EmptyState.Header now supports `as` and `looksLike`
- Run Storybook
- Verify the props work at: http://localhost:9001/?path=/story/layout-empty-state--basic-empty-state
=> UX-412 Add support for EmptyState.Header 'as' and 'looksLike'

packages/matchbox/src/components/Page/Page.js
- Fixes bug where chevron is not aligned with breadcrumbs in `Page` component
- Verify stories at http://localhost:9001/?path=/story/layout-page--basic-example
=> UX-431 Align chevron in Page component breadcrumbs

cypress/integration/Modal.spec.js, packages/matchbox/src/components/Modal/Modal.js
- Adds `returnFocus` to the Modal's FocusLock container component
- Closes #730
- Verify e2e tests pass
- Run storybook, and visit the *iframe*: http://localhost:9001/iframe.html?id=overlays-modal--toggle-example
- Verify focus is returned to the Open Modal button when closing
=> Resolve Issue-730 Add 'returnFocus' prop to Modals focus lock container

.storybook/config.js, packages/matchbox/package-lock.json, packages/matchbox/package.json, packages/matchbox/src/components/Button/Button.js, packages/matchbox/src/components/Drawer/Drawer.js, packages/matchbox/src/components/Modal/Modal.js, packages/matchbox/src/components/Popover/PopoverContent.js, packages/matchbox/src/components/Tooltip/Tooltip.js
- Enables React.StrictMode - in order to log additional warning messages and adhere to best practices
- Upgrades react-transition-group, which was using a deprecated use `findDomNode`
- Run storybook and verify all transitions are still working on:
- Button loading animation
- Drawer
- Modal
- Popover
- Tooltip
=> UX-404 Upgrades react-transition-group to resolve deprecated use of findDomNode

package-lock.json, packages/matchbox/src/components/Button/Button.js, packages/matchbox/src/components/Button/tests/Button.test.js, site/src/pages/components/button.mdx, stories/action/Button.stories.js
- new `as` prop which replaces `component` and `Component`
- `component` and `Component` props are deprecated 
- updates tests to use `as`
- verify `As` button story
=> UX-411 Button should accept "as" and deprecate "component"

packages/matchbox/src/components/Tabs/Tab.js, packages/matchbox/src/components/UnstyledLink/UnstyledLink.js, packages/matchbox/src/components/UnstyledLink/tests/UnstyledLink.test.js, site/src/pages/components/unstyledlink.mdx, stories/navigation/UnstyledLink.stories.js
- Adds new `as` prop to UnstyledLink
- Deprecates `component`
- Update tests to verify new `as` prop while testing backward compatibility
- Verify stories at http://localhost:9001/?path=/story/navigation-unstyledlink--with-wrapper-components
=> UX-433 UnstyledLink add 'as' prop and deprecate 'component'

packages/matchbox/src/components/EmptyState/EmptyState.js, packages/matchbox/src/components/EmptyState/Media.js, packages/matchbox/src/components/EmptyState/tests/EmptyState.test.js, stories/layout/EmptyState.stories.js
- New `EmptyState.Media` Component
- Allows both `Picture` and `Video` 
- configurable `maxWidth` prop
- Verify EmptyState stories at http://localhost:9001/?path=/story/layout-empty-state--empty-state-with-media
- https://sparkpost.atlassian.net/browse/UX-426
=> UX-422 add new EmptyState.Media to allow Video or Picture elements

site/src/routes/routes.json
- Adds the missing Toggle route to the side nav
- Run the site with `npm run start:site` and verify `Toggle` is in the nav
=> UX-424 Add Toggle to routes file

cypress/integration/usePrefersColorScheme.spec.js, packages/matchbox/src/hooks/index.js, packages/matchbox/src/hooks/usePrefersColorScheme.js, stories/utility/usePrefersColorScheme.stories.js
- new `usePrefersColorScheme` hook
- returns either `light` or `dark`
- Verify story http://localhost:9001/?path=/story/utility-usepreferscolorscheme--example-usage
- Testing with Chrome:
- System Preferences -> General -> Appearance:Dark (toggle between these two and the story will update)
=> UX-260 Create usePrefersColorScheme hook

cypress/integration/Checkbox.spec.js, cypress/integration/ListBox.spec.js, cypress/integration/Select.spec.js, cypress/integration/TextField.spec.js, packages/matchbox/src/components/Checkbox/Checkbox.js, packages/matchbox/src/components/ListBox/ListBox.js, packages/matchbox/src/components/Radio/Radio.js, packages/matchbox/src/components/Select/Select.js, packages/matchbox/src/components/TextField/TextField.js, stories/form/ListBox.stories.js
- Adds `aria-invalid` on all `<input>` components that support errors
- Skips `Toggle` and `RadioCard`
- Verify `aria-invalid` is properly set on:
- Checkbox
- Radio 
- Select
- TextField
- ListBox
=> UX-432 Add aria-invalid to Checkbox Radio Select Textfield and ListBox

cypress/integration/Checkbox.spec.js, cypress/integration/ListBox.spec.js, cypress/integration/Select.spec.js, cypress/integration/TextField.spec.js, packages/matchbox/src/components/Error/Error.js, packages/matchbox/src/components/Error/tests/Error.test.js
- Hardcodes `data-id="error-message"` to the `Error` component
- Surfaced in: TextField, Checkbox, Select, ListBox
- Verify the attribute is set correctly on the error message
=> UX-439 Add data-id to Error component

cypress/integration/UnstyledLink.spec.js, packages/matchbox/src/components/UnstyledLink/UnstyledLink.js
- Directly adds system props to UnstyledLink, since the props weren't being forwarded to Text
- Visit http://localhost:9001/iframe.html?id=navigation-unstyledlink--with-text-props
- Verify Cypress tests pass
=> UX-447 Fix  UnstyledLink system props

packages/matchbox/src/components/Snackbar/Snackbar.js, packages/matchbox/src/components/Snackbar/tests/Snackbar.test.js, stories/feedback/Snackbar.stories.js
- Snackbar component now accepts `maxWidth` prop as a styled prop and not just a number
- Verify Snackbar [story](http://localhost:9001/?path=/story/feedback-snackbar--large)
=> UX-444 Update Snackbar component props to accept maxWidth styled prop

packages/matchbox/src/components/Error/Error.js
- Fixes vertical alignment of `Error` component
- Verify stories with errors http://localhost:9001/?path=/story/form-textfield--with-an-error
=> UX-443 Vertical align `Error` icon and text

packages/matchbox/src/components/Page/Page.js, packages/matchbox/src/components/Snackbar/Snackbar.js, packages/matchbox/src/components/Snackbar/tests/Snackbar.test.js, stories/feedback/Snackbar.stories.js
- `Page` actions now have `300` spacing instead of `500` to comply with patterns
- Verify Page [stories](http://localhost:9001/?path=/story/layout-page--basic-example)
=> UX-446 Change <Page> action spacing from 500 to 300

packages/matchbox/src/components/Expandable/Expandable.js, packages/matchbox/src/components/Expandable/styles.js, stories/layout/Expandable.stories.js
update vertical padding on Expandable with Subtitle
- updated vertical padding of `Expandable` with `subtitle` to match horizontal spacing
- Verify story http://localhost:9001/?path=/story/layout-expandable--with-image-title-and-subtitle
=> UX-445 Expandable update vertical padding with subtitle

packages/matchbox/src/components/ProgressBar/ProgressBar.js
- Removes spreading of unknown props on ProgressBar
- Explicitly picks system props
- Verify ProgressBar story renders as expected: http://localhost:9001/?path=/story/feedback-progressbar--default
- Verify ProgressBar tests did not break
- Verify 2web2ui does not use any props that are not explicitly defined: https://proply-2web2ui.vercel.app/
=> UX-394 Remove spreading of unknown ProgressBar props

packages/matchbox/src/components/Snackbar/Snackbar.js, packages/matchbox/src/components/Snackbar/tests/Snackbar.test.js
- Removes spreading of unknown props on Snackbar
- Explicitly picks system props
- Verify story renders as expected: http://localhost:9001/?path=/story/feedback-snackbar--responsive-system-props
- Verify tests did not break
- Verify 2web2ui does not use any props that are not explicitly defined: https://proply-2web2ui.vercel.app/
=> UX-397 Remove spreading of unknown Snackbar props

packages/matchbox/src/components/Checkbox/Checkbox.js, packages/matchbox/src/components/ComboBox/ComboBoxTextField.js, packages/matchbox/src/components/ListBox/ListBox.js, packages/matchbox/src/components/Radio/Radio.js, packages/matchbox/src/components/Select/Select.js, packages/matchbox/src/components/TextField/TextField.js, stories/form/Checkbox.stories.js, stories/form/ComboBox.stories.js, stories/form/Radio.stories.js
- Moved `error` below `helpText` in `Select`, `ComboBox`, `ListBox`, `Checkbox`, `Radio`, Select`, and `TextField`
- Updated stories to include examples with help text and an error
- Verify form stories
- `Checkbox`: http://localhost:9001/?path=/story/form-checkbox--with-error-and-help-text
- `ComboBox`: http://localhost:9001/?path=/story/form-combobox--text-field-with-error-and-help-text
- `ListBox`: http://localhost:9001/?path=/story/form-combobox--text-field-with-error-and-help-text 
- `Radio`: http://localhost:9001/?path=/story/form-radio--with-error-and-help-text
- `Select`: http://localhost:9001/?path=/story/form-select--with-help-text-and-error
- `TextField`: http://localhost:9001/?path=/story/form-textfield--help-text-and-error
=> UX-450 move error below help text in form components

packages/matchbox/src/components/Banner/Banner.js, packages/matchbox/src/components/Banner/tests/Banner.test.js
- Removes spreading of unknown props on Banner
- Explicitly picks system props
- Verify story renders as expected: http://localhost:9001/?path=/story/feedback-banner--default-banner
- Verify tests did not break
- Verify 2web2ui does not use any props that are not explicitly defined: https://proply-2web2ui.vercel.app/
=> UX-395 Remove spreading of unknown Banner props

packages/matchbox/src/components/Panel/Header.js, packages/matchbox/src/components/Panel/Panel.js, packages/matchbox/src/components/Panel/Section.js, packages/matchbox/src/components/Panel/SubHeader.js, packages/matchbox/src/components/Panel/context.js, packages/matchbox/src/components/Panel/tests/Panel.test.js, stories/layout/Panel.stories.js
- New `appearance` prop on `Panel` component which accepts `inverted` or `default`
- Implemented with context to pass down to `Panel.Header` `Panel.SubHeader` and `Panel.Section`
- Verify `Panel` stories http://localhost:9001/?path=/story/layout-panel--inverted-appearance
=> UX-430 Create inverted color scheme for Panel component

packages/matchbox/src/components/Tag/Tag.js, packages/matchbox/src/components/Tag/tests/Tag.test.js
- Removes spreading of unknown props on Tag
- Explicitly picks system props
- Adds data-id and forwardRef
- Verify story renders as expected: http://localhost:9001/?path=/story/feedback-tag--colors
- Verify tests did not break
- Verify 2web2ui does not use any props that are not explicitly defined: https://proply-2web2ui.vercel.app/
=> UX-452 Remove spreading of unknown Tag props

packages/matchbox/src/components/Panel/Section.js, packages/matchbox/src/components/Panel/tests/Panel.test.js
- Fixes a bug that prevented empty `Panel.Section` from rendering
- Run storybook and visit a Panel story: http://localhost:9001/?path=/story/layout-panel--with-a-header
- Try rendering an empty panel section with no children
=> UX-465 Fix empty Panel.Section rendering

packages/matchbox/src/components/Tabs/Tab.js, packages/matchbox/src/components/Tabs/tests/Tabs.test.js
This PR isn't pointed to `main` because we want to publish a patch on top of `4.8.1`. The main branch contains changes that would need a minor release.
- Fixes tab styling on Safari
- Open Safari and run storybook
- Visit: http://localhost:9001/?path=/story/navigation-tabs--example-tabs
- Verify the first 3 tabs have `type=button`, and the last one does not
- Verify styles are correct
=> UX-469 Fix Tabs on Safari

packages/matchbox/src/components/Tabs/styles.js, stories/navigation/Tabs.stories.js
- Fixes a bug that caused excessive horizontal scroll on the viewport when tabs are overflowing
- Run storybook and visit: http://localhost:9001/iframe.html?id=navigation-tabs--example-tabs
- Down size the browser, attempt to scroll horizontally with a trackpad on the window
- Verify the browser does **not** scroll horizontally
=> UX-470 Fix bug that caused excessive horizontal scroll on Tabs

packages/matchbox/src/components/Checkbox/styles.js
- bugfix: prevent hover styles from applying to disabled checkboxes
- Verify disabled checkbox story http://localhost:9001/?path=Checkbox__disabled&source=false
=> UX-467 Disabled checkboxes should ignore hover event

cypress/integration/Tab.spec.js, libby/navigation/Tabs.lib.js, packages/matchbox/src/components/Tabs/Tab.js
- Adds new `as` prop to `Tab` component
- Deprecate `component` and `Component` props on `Tab` component
- Verify tabs stories http://localhost:9001/?path=Tabs__automatic-keyboard-activation&source=false
=> UX-448 Tabs should support component wrapper via as

cypress/integration/Select.spec.js, libby/form/Select.lib.js, packages/matchbox/src/components/Select/Select.js, site/src/pages/components/select.mdx
Resolves #788 
- Adds `labelHidden` to Select
- Run libby, visit http://localhost:9001/?path=Select__hidden-label&source=false
- Verify the label is present to screen readers, but visually hidden
=> Resolves #788 Support labelHidden on Select

packages/matchbox/src/components/Pager/Pager.js, packages/matchbox/src/components/Pager/tests/Pager.test.js
- Removes spreading of unknown Pager props
- Pager.Next and Pager.Previous are wrappers around Button, so no need to touch those
- Passes through id and data-id
- Verify no additional props are used in app: https://proply-2web2ui.vercel.app/
- Verify margin props, id, data-id are passed through correctly
-
=> UX-457 Remove spreading of unknown Pager props

libby/action/ActionList.lib.js, packages/matchbox/src/components/ActionList/Action.js, packages/matchbox/src/components/ActionList/tests/ActionList.test.js
- Removes the `is="checkbox"` option from `ActionList.Action`
- Verify mdx docs are up to date (they never included the option)
- Verify 2web2ui does not use the option
=> UX-482 Remove is="checkbox" option from ActionList.Action

cypress/integration/Expandable.spec.js, libby/layout/Expandable.lib.js, packages/matchbox/src/components/Expandable/Expandable.js
- Removes spreading of unknown Expandable props
- Passes through data-id to the outermost wrapper
- Verify no additional props are used in app: https://proply-2web2ui.vercel.app/
- Verify margin props, data-id are passed through correctly
-
=> UX-453 Remove spreading of unknown Expandable props

cypress/integration/ActionList.spec.js, libby/action/ActionList.lib.js, packages/matchbox/src/components/ActionList/ActionList.js
- Removes spreading of unknown ActionList props
- Verify no additional props are used in app: https://proply-2web2ui.vercel.app/
=> UX-461 Remove spreading of unknown ActionList props

libby/overlays/Modal.lib.js, packages/matchbox/src/components/Modal/Content.js, packages/matchbox/src/components/Modal/Header.js, packages/matchbox/src/components/Modal/Modal.js, packages/matchbox/src/components/Modal/context.js
- Replaces the unnecessary `getChild` or cloning with React context to allow for more flexible component composition
- Visit http://localhost:9001/?path=Modal__toggle-example&source=false
- Verify clicking on the close button in the header works
=> UX-474 Allow any Modal children

packages/matchbox/src/components/Tabs/styles.js
- Tab focus state now uses `focus-visible`
- A fallback is provided for browsers that don't support `focus-visible`
- Run libby with `npm run start:libby`
- Visit http://localhost:9001/?path=Tabs__automatic-keyboard-activation&source=false
- Verify clicking on tabs does not produce tab outlines
- Verify keyboard navigation does produce tab outlines
=> UX-468 Tab focus state uses focus-visible with fallback

cypress/integration/Skeleton.spec.js, libby/feedback/Skeleton.lib.js, packages/matchbox/src/components/Skeleton/Skeleton.js
- Adds `aria-hidden` to Skeleton components
- Run libby with `npm run start:libby`
- Visit: http://localhost:9001/?path=Skeleton__all-together&source=false
- Verify the skeleton elements are not tabbable and have `aria-hidden` set
=> UX-483 Skeletons are hidden from screen readers

cypress/integration/Table.spec.js, libby/layout/Table.lib.js, packages/matchbox/src/components/Table/Table.js, packages/matchbox/src/components/Table/TableElements.js, packages/matchbox/src/components/Table/tests/Table.test.js
- Removes spreading of unknown Table component props
- Supports new HTML attributes for accessibility
- Run libby, verify the table works as expected http://localhost:9001/?path=Table__all-table-components&source=false
- Verify 2web2ui does not use any attributes that aren't defined
=> UX-479 Remove spreading of unknown Table component props, Forwards refs to all Table components

cypress/integration/Drawer.spec.js, libby/overlays/Drawer.lib.js, packages/matchbox/src/components/Drawer/Drawer.js, packages/matchbox/src/components/Drawer/Footer.js, packages/matchbox/src/components/Drawer/Header.js, packages/matchbox/src/components/Drawer/context.js, packages/matchbox/src/components/Drawer/tests/Drawer.test.js, packages/matchbox/src/components/Drawer/tests/Header.test.js
- Allows any React node to be a child of Drawer, to support more flexible component composition
- Run Libby - visit: http://localhost:9001/?path=Drawer__example-drawer&source=false
- Verify the first drawer renders and functions correctly
=> UX-449 Allow any Drawer children

cypress/integration/Popover.spec.js, packages/matchbox/src/components/Popover/Popover.js, packages/matchbox/src/helpers/focus.js, packages/matchbox/src/helpers/tests/focus.test.js
- Focuses on the popover activator's focusable child when closing the popover
- Run libby
- Visit the stories for both controlled and uncontrolled popovers 
- http://localhost:9001/?path=Popover__controlled&source=false
- http://localhost:9001/?path=Popover__uncontrolled&source=false
- Verify focus is returned when
- closing via clicking outside
- closing via pressing escape
- closing via close button (for controlled popover)
=> UX-492 Focus on activator when Popovers close

packages/matchbox/src/components/RadioCard/RadioCard.js, packages/matchbox/src/components/RadioCard/styles.js
- Removes the indent
- Adds white background color (this was missing from original implementation)
- Run libby and visit http://localhost:9001/?path=RadioCard__grid&source=false
- Verify support text is not indented
=> UX-489 Remove indent on RadioCard component

config/test-utils.js, jest.config.json, package-lock.json, package.json, packages/matchbox/src/components/Checkbox/Checkbox.js, packages/matchbox/src/components/Checkbox/Group.js, packages/matchbox/src/components/ComboBox/ComboBoxTextField.js, packages/matchbox/src/components/ComboBox/tests/ComboBox.test.js, packages/matchbox/src/components/Label/Label.js, packages/matchbox/src/components/Label/tests/Label.test.js, packages/matchbox/src/components/ListBox/ListBox.js, packages/matchbox/src/components/Radio/Group.js, packages/matchbox/src/components/Radio/Radio.js, packages/matchbox/src/components/Radio/tests/Group.test.js, packages/matchbox/src/components/RadioCard/Group.js, packages/matchbox/src/components/Select/Select.js, packages/matchbox/src/components/Select/tests/Select.test.js, packages/matchbox/src/components/TextField/TextField.js
Closes #810
- Removes the check in the Label component that returns `null` if no `label` is provided
- Deprecates `label`
- Updates components that use `Label`
- Installs react-testing-library
- Refactor a few tests
- Run libby, and visit the following component pages to verify Label works as expected:
- TextField
- Select
- Checkbox
- Radio
- ListBox
- ComboBox
=> Resolves #810 – Support Label children over label prop

packages/matchbox/src/components/Label/Label.js, packages/matchbox/src/components/Label/tests/Label.test.js
Closes #811 
- Passes through `htmlFor` and `id` if both is provided
- Defaults to old behavior if only `id` is provided
- Verify tests pass, we thoroughly test if ids are working properly through tests
=> Resolves #811 Support Label htmlFor

config/test-utils.js, libby/feedback/Skeleton.lib.js, packages/matchbox/src/components/Skeleton/Skeleton.js, packages/matchbox/src/components/Skeleton/tests/Skeleton.test.js
- Passes through `data-id` to all Skeleton components
- Prevents `children` from being passed down to Skeleton.Box
- Run libby
- Visit the skeleton stories: http://localhost:9001/?path=Skeleton__body&source=false
- Verify `data-id` is passed along to the DOM
=> UX-491 Pass through data-id to all Skeletons, Prevent rendering children

libby/action/Button.lib.js, packages/matchbox/src/components/Button/Button.js, packages/matchbox/src/components/Button/tests/utils.test.js, packages/matchbox/src/components/Button/utils.js
Closes #820
- Fixes Button loader colors for non-filled buttons
- Run libby, visit http://localhost:9001/?path=Button__loading&source=false
- Verify the loading `Spinner`s are visible and use the right colors
=> Resolves #820 Fix button loader colors

cypress/integration/ListBox.spec.js, libby/form/ListBox.lib.js, packages/matchbox/src/components/ListBox/ListBox.js, packages/matchbox/src/components/ListBox/tests/ListBox.test.js
- Passes through `id` `name` `data-id` and `data-sensitive` to Listbox's hidden input
- Fixes the `onFocus` and `onBlur` events
=> UX-502 Add name id and data attributes to hidden field in Listbox

packages/matchbox/src/components/ActionList/ActionList.js, packages/matchbox/src/components/ActionList/tests/ActionList.test.js
- Passes through all ActionList props to support downshift
- Verify non-declared props are passed along, such as `id` `role` or an `aria` attribute
=> UX-507 Pass through all ActionList props for downshift

libby/layout/Table.lib.js, packages/matchbox/src/components/Table/SortButton.js, packages/matchbox/src/components/Table/TableElements.js, packages/matchbox/src/components/Table/styles.js
- Removes the flex declaration that prevented SortButtons from being horizontally aligned
- Adds new `align` prop to Cell and HeaderCell (wrapper around textAlign)
- Run libby
- Visit http://localhost:9001/?path=Table__all-table-components&source=false
- Verify text align prop works
=> UX-503 Adds new `align` prop to Cell and HeaderCell

cypress/integration/Popover.spec.js, packages/matchbox/src/components/Popover/Popover.js
- Adjusts the initial incorrect implementation – activators shouldn't be focused when clicking outside
- Visit http://localhost:9001/?path=Popover__controlled&source=false
- The activator button should not be focused by default
- The activator button should only focus when pressing escape when open
=> UX-510 Fix Popover activators being focused by default

packages/matchbox/src/components/Toggle/Toggle.js, packages/matchbox/src/components/Toggle/tests/Toggle.test.js
- Passes through unknown props to Toggle's input element
- Visit http://localhost:9001/?path=Toggle__renders-correctly&source=false
- Verify unknown props, like data attributes, are passed through
=> UX-511 Correctly pass through props to Toggle input

libby/form/Slider.lib.js, packages/matchbox/src/components/Slider/Slider.js, packages/matchbox/src/components/Slider/styles.js
Closes #833 
- Slider ticks with spaces should no longer wrap
- Slider ticks and the beginning and end of the slider should no longer overflow
- Slider supports `aria-labelledby`
- Run libby
- Visit http://localhost:9001/?path=Slider__with-ticks&source=false
- Verify the tick labels dont wrap, and that the first and last tick labels don't overflow (they should be left and right aligned).
=> UX-517 Fix wrapping and alignment on Slider ticks

cypress/integration/ListBox.spec.js, libby/form/ListBox.lib.js, packages/matchbox/src/components/ListBox/Option.js
- Prevent form from submitting when choosing a `ListBox` option
- New test to verify form is not being submitted
- Verify new example in libby http://localhost:9001/?path=ListBox__in-parent-form&source=false
- Verify cypress tests pass and form is not submitted
=> UX-518 prevent form from submitting when ListBox value is changed

packages/matchbox/src/components/Checkbox/Checkbox.js, packages/matchbox/src/components/Checkbox/tests/Checkbox.test.js, packages/matchbox/src/components/ListBox/ListBox.js, packages/matchbox/src/components/ListBox/tests/ListBox.test.js, packages/matchbox/src/components/Radio/Group.js, packages/matchbox/src/components/Radio/tests/Group.test.js, packages/matchbox/src/components/Select/Select.js, packages/matchbox/src/components/Select/tests/Select.test.js, packages/matchbox/src/components/TextField/TextField.js, packages/matchbox/src/components/TextField/tests/TextField.test.js
- Removes the visual `*` required indicator from all fields
- Run libby
- Visit the following stories:
- Select
- Textfield
- Checkbox
- Radio.Group 
- ListBox
- Verify that when they are required, they apply the `required` HTML attribute but do not render anything visually
- Verify that no other input components are missing this change
=> UX-508 Remove visual indicator for required fields

cypress/integration/Slider.spec.js, libby/form/Slider.lib.js, packages/matchbox/src/components/Slider/Slider.js
Closes #836 
- No longer prevents events from bubbling up unless they are hitting keys associated with controlling the slider
- Run libby
- Visit the Slider story
- Verify that focus is not trapped when pressing Tab. Up and down arrow keys should still prevent window scrolling.
=> issue-836 Sliders should no longer trap focus

packages/matchbox/src/components/Tooltip/Tooltip.js, packages/matchbox/src/components/Tooltip/tests/Tooltip.test.js
- Lowers font-size and line height on tooltips to `100` from `200`
- Lowers padding on tooltips to `200` from `300`
=> UX-530 Lower default tooltip sizing

cypress/integration/Table.spec.js, libby/layout/Table.lib.js, packages/matchbox/package-lock.json, packages/matchbox/package.json, packages/matchbox/src/components/Table/SortButton.js, packages/matchbox/src/components/Table/Table.js, packages/matchbox/src/components/Table/TableElements.js, packages/matchbox/src/components/Table/styles.js, packages/matchbox/src/components/Table/tests/Table.test.js
- Popovers now work inside a tables first frozen column
- Renders a duplicate table to handle the overflow properties
- First column of the underlying table is hidden, and subsequent columns of the overlay table are hidden with CSS
- Also bottom aligns the table headers
- Run Libby
- Visit http://localhost:9001/?path=Table__frozen-first-column
- Verify popovers work in the first column
=> UX-533 Support popovers in frozen columns

cypress/integration/ActionList.spec.js, cypress/integration/ListBox.spec.js, cypress/integration/Popover.spec.js, cypress/integration/Tab.spec.js, cypress/integration/Table.spec.js, libby/overlays/Popover.lib.js, packages/matchbox/src/components/ActionList/Action.js, packages/matchbox/src/components/ActionList/ActionList.js, packages/matchbox/src/components/ActionList/styles.js, packages/matchbox/src/components/ComboBox/tests/ComboBox.test.js, packages/matchbox/src/components/Popover/Popover.js, packages/matchbox/src/components/Popover/PopoverContent.js, packages/matchbox/src/components/Popover/PopoverOverlay.js, packages/matchbox/src/components/Portal/Portal.js, packages/matchbox/src/components/Table/Table.js, packages/matchbox/src/components/Table/styles.js, packages/matchbox/src/components/Table/tests/Table.test.js, packages/matchbox/src/helpers/focus.js, packages/matchbox/src/helpers/string.js
- Changes the behavior of Popovers
- Popovers are now rendered in a `Portal`
- Popovers now correctly focus on a focusable child when opening
- Popovers now open when hitting the up or down arrows when uncontrolled
- Popovers now close when pressing tab (via a new prop)
- ActionList
- ActionLists are now keyboard navigable with the up and down arrows
- ActionLists now properly set `role="menuitem"` and `role="menu"`
- Table
- Tables now only render one table with the `freezeFirstColumn` prop
- Run libby
- Visit http://localhost:9001/?path=Popover__with-an-ActionList
- Verify the changes above
- On: http://localhost:9001/?path=Popover__uncontrolled
- Verify the popover container is focused when opened
- On: http://localhost:9001/?path=Popover__controlled
- Verify the close button is …
=> UX-565 Massively change ActionList and Popover interactions

libby/form/TextField.lib.js, packages/matchbox/src/components/Error/Error.js
Closes #878 
Top aligns the icon in the Error component:
- Run libby
- Visit any input story with the error component
- Try adding a long error message
- Verify the icon is top aligned
=> Resloves #878 Fix error label icon alignment

packages/matchbox/src/components/Popover/PopoverOverlay.js
- Update positioning values for `PopoverOverlay` when popover is open or closed
- Verify the Popover [Story](http://localhost:9001/?path=Popover__positioning) 
- Open and close the popover, make the window smaller, and try scrolling to the right. Before the page would overflow because the overlay element positioning had not been updated
=> UX-584 Fix Popover Overlay bug

packages/matchbox/src/components/Checkbox/Group.js, packages/matchbox/src/components/Checkbox/tests/Group.test.js, packages/matchbox/src/components/Radio/Group.js, packages/matchbox/src/components/Radio/tests/Group.test.js
=> Resolves #879 & #880 – Support data-id and className in input groups

libby/layout/Panel.lib.js, packages/matchbox/src/components/Panel/Action.js
Closes #894 
- Supports the Button `color` prop in `Panel.Actions`
- Run libby and verify the red action works: http://localhost:9001/?path=Panel__actions
=> Resolves #894 Support color in panel actions

packages/matchbox/src/components/Banner/Banner.js, packages/matchbox/src/components/Banner/styles.js, packages/matchbox/src/components/Banner/tests/Banner.test.js
- Restyles Banners to match these mockups: https://www.figma.com/file/juWNBofvmmQBLABf2PPBWY/Page-Header-Rework?node-id=4%3A566
- Run Libby and visit this story: http://localhost:9001/?path=Banner__success-Banner
- Verify styling matches the Figma mockup
=> UX-598 Restyle large Banners

libby/overlays/Popover.lib.js, packages/matchbox/src/components/Page/Page.js, packages/matchbox/src/components/Popover/Popover.js, packages/matchbox/src/components/Popover/PopoverContent.js, packages/matchbox/src/components/Popover/styles.js, packages/matchbox/src/helpers/propTypes.js
- Popover now accepts a `position` prop
- Deprecates `left`, `right`, `top`, `bottom`
- Deprecated prop warnings wont be logged in tests anymore
- Verify these still work: http://localhost:9001/?path=Popover-deprecated__positioning
- Verify these work: http://localhost:9001/?path=Popover__positioning
=> UX-500 Add new `position` prop to `Popover`

packages/matchbox/src/helpers/keyEvents.ts
- Converts `keyEvent` helpers to typescript
- Verify all tests and build pass
=> UX-682 Convert keyEvent helpers to typescript

cypress/integration/Modal.spec.js, packages/matchbox/src/components/Modal/Legacy.js
- Fixes interaction inside Legacy Modals
- Visit http://localhost:9001/?path=Modal-Deprecated__legacy-usage
- Verify the modal is clickable and that the overlay is visible
=> UX-694 Fix Legacy Modals

cypress/integration/ActionList.spec.js, libby/action/ActionList.lib.tsx, packages/matchbox/src/components/ActionList/Action.tsx
- Fixes a bug that rendered both `content` and `children` inside Actionlist Actions
- Verify tests pass correctly or visit http://localhost:9001/?path=ActionList-Deprecated__should-only-render-either-content-or-children
=> UX-696 Only render either content or children in ActionLists

libby/utility/WindowEvent.lib.tsx, packages/matchbox/src/components/WindowEvent/WindowEvent.tsx, packages/matchbox/src/hooks/useWindowEvent.ts
- WindowEvent and useWindowEvent are properly typed 
- Open the window event libby story on VSCode
- Ensure that the passed `event` for both stories are correctly typed as `KeyboardEvent`
=> UX-701 Window event should correctly type its event parameter

packages/matchbox/src/components/ActionList/ActionList.tsx, packages/matchbox/src/components/Drawer/Drawer.tsx, packages/matchbox/src/components/Popover/Popover.tsx, packages/matchbox/src/helpers/keyEvents.ts
- Key event helpers now support global window/document key events as well as React key events
- Verify the build passes and that there are no typescript errors
-
=> UX-705 Support both window and react key events in keyEvent helpers

cypress/regression/ActionList.spec.js, cypress/regression/Drawer.spec.js, libby/regression/Drawer.lib.tsx
- Adds a new story for Drawer regression testing
- Run Libby
- Run `npm run test:regression:headless` to run Percy snapshots
- Log into Percy and verify the snapshots are uploaded
- Here is a test build: https://percy.io/efff6832/matchbox/builds/12939422/changed/731207350
=> UX-708 Take Percy snapshots of the Drawer component

libby/form/TextField.lib.tsx, packages/matchbox/src/components/TextField/TextField.tsx, packages/matchbox/src/helpers/types.ts
- TextField now correctly accepts ReactNodes in the `prefix` field
- Try to add any ReactNode (or Icon) to the `prefix` field
- There should be no TS errors
=> UX-714 Fix prefix type on TextField

libby/form/TextField.lib.tsx, packages/matchbox/src/components/ListBox/ListBox.tsx, packages/matchbox/src/components/ListBox/tests/ListBox.test.js
- Lowers the Popover `minWidth` of the ListBox component
- Hides `label` if no label is provided
- Run libby
- Open up the TextField story with connections
- It should look like this:
=> UX-715 Fix ListBox minWidth and label rendering

cypress/regression/Tabs.spec.js, libby/regression/Tabs.lib.tsx, packages/matchbox/src/components/Tabs/styles.ts
- Fixes the issue of custom tab wrappers with left aligned text
- Adds Percy snapshots for tabs at desktop and mobile
- Verify the snapshots in Percy - https://percy.io/efff6832/matchbox/builds/13071247/changed/738334520
=> UX-712 Fix center aligned custom Tabs, Add Percy snapshots for tabs

packages/matchbox/src/components/WindowEvent/WindowEvent.tsx, packages/matchbox/src/helpers/noop.ts, packages/matchbox/src/helpers/tests/noop.test.js, packages/matchbox/src/helpers/window.ts, packages/matchbox/src/hooks/useBreakpoint.ts, packages/matchbox/src/hooks/useInView.ts, packages/matchbox/src/hooks/usePrefersColorScheme.ts, packages/matchbox/src/hooks/usePrefersReducedMotion.ts, packages/matchbox/src/hooks/useWindowEvent.ts
- Checks if `window` exists before rendering certain components or running hooks 
- Need to figure out how to verify this easily
=> UX-724 Check browser before performing browser specific operations

packages/design-tokens-sd/config.js, packages/design-tokens-sd/utils/utils.js
- Generates two javascript exports
- `tokens.legacy.js` - Existing naming convention eg `borderWidth_200`
- `tokens.js` - NEW snake-case only names
- Run `npm run build` inside the `design-tokens-sd` package
- Verify the javascript exports are generated correctly
=> UX-749 Generate JS token files

packages/matchbox/src/components/Button/Button.tsx
- Removes the `loading` prop from parent `Button` elements to fix a console error
- Run libby and visit the button loading story
- Verify you do not see this message in the console:
```
Warning: Received `true` for a non-boolean attribute `loading`.
```
=> UX-729 Prevent button loading prop from rendering in DOM

libby.config.js
- Adds the `transpileOnly` flag to libby's ts-loader config to massively speed up TS compilation
- This means that type-checking will not happen when running Libby locally, but we will still have type-checking through the Github workflow (which runs a production build)
- Run `npm run start:libby` 
- Start up time should be noticeably faster
=> UX-759 Add transpileOnly ts-loader flag for development

packages/matchbox/src/components/Button/Button.tsx
- Fixes the `to` prop's type so that it accepts objects for react-router support
- Try to use an object within Button's `to` prop, verify it does not produce an error
=> UX-760 Fix button `to`  types

packages/matchbox/src/components/Button/Icon.tsx
- Removes an unused type from `Button.Icon`
- Verify adding children to `Button.Icon` results in an error
=> UX-761 Remove children from Button.Icon types

packages/matchbox/src/components/Column/Column.tsx
- Removes an unused type from the Column component
- Verify the `reverse` prop is not available to `Column`
=> UX-762 (Type fix) Remove reverse prop from Column

packages/design-tokens/index.scss, packages/design-tokens/tokens.scss
- Adds the legacy `tokens.scss` file to the design tokens package. This was used by some applications to import tokens.
- Adds  a new `index.scss` file to the design tokens package.
- The old file: https://github.com/SparkPost/matchbox/pull/1029/files#diff-7de20171f753783af812d7ada1b4ad49fab5e63dc4e4ba9a375cc513cba30c84
- Verify the files import the correct scss files
=> UX-771 Fix design token scss import

libby/form/RadioCard.lib.tsx, libby/regression/RadioCard.lib.tsx, packages/matchbox/src/components/RadioCard/Group.tsx, packages/matchbox/src/components/RadioCard/RadioCard.tsx, packages/matchbox/src/components/RadioCard/styles.ts, packages/matchbox/src/components/RadioCard/tests/RadioCard.test.js
- Adds new `size` prop to `RadioCard` which accepts `small`
- Adds new `space` prop to RadioCard.Group` which accepts `compact`
- Run Libby, visit http://localhost:9001/?path=RadioCard__small-variant
- Verify the component matches the mockups: https://www.figma.com/file/kbeuqghvpagMmaLWwqszQo/Forms?node-id=260%3A268
=> UX-777 Add small radio card variant

cypress/regression/CheckboxCard.spec.js, libby/form/CheckboxCard.lib.tsx, libby/regression/CheckboxCard.lib.tsx, package-lock.json, package.json, packages/matchbox/src/components/CheckboxCard/CheckboxCard.tsx, packages/matchbox/src/components/CheckboxCard/Group.tsx, packages/matchbox/src/components/CheckboxCard/index.ts, packages/matchbox/src/components/CheckboxCard/styles.ts, packages/matchbox/src/components/CheckboxCard/tests/CheckboxCard.test.js, packages/matchbox/src/components/RadioCard/tests/RadioCard.test.js, packages/matchbox/src/components/index.tsx
- Adds `CheckboxCard` and `CheckboxCard.Group` components
- Run libby and visit: http://localhost:9001/?path=CheckboxCard__basic-usage
- Verify all the stories work correctly
- Verify the component matches the mockups: https://www.figma.com/file/kbeuqghvpagMmaLWwqszQo/Forms?node-id=279%3A269
=> UX-253 Add CheckboxCard component

packages/matchbox/src/components/Table/SortButton.tsx
- Bottom aligns icons within table sort buttons
- Run libby and visit http://localhost:9001/?path=Table__all-table-components
- Verify the arrow icons are bottom aligned with
=> UX-780 Bottom align sort button icons

libby/form/CheckboxCard.lib.tsx, libby/form/RadioCard.lib.tsx, libby/regression/CheckboxCard.lib.tsx, libby/regression/RadioCard.lib.tsx, packages/matchbox/src/components/CheckboxCard/Group.tsx, packages/matchbox/src/components/CheckboxCard/tests/CheckboxCard.test.js, packages/matchbox/src/components/RadioCard/Group.tsx, packages/matchbox/src/components/RadioCard/tests/RadioCard.test.js
- Adds new `helpText` prop to `RadioCard.Group` and `CheckboxCard.Group`
- Run libby
- visit http://localhost:9001/?path=RadioCard__help-text
- and visit http://localhost:9001/?path=CheckboxCard__help-text
- Verify the prop works correctly
=> UX-779 Add helpText prop to RadioCard.Group and CheckboxCard.Group

libby/form/CheckboxCard.lib.tsx, packages/matchbox/src/components/CheckboxCard/CheckboxCard.tsx, packages/matchbox/src/components/CheckboxCard/styles.ts, packages/matchbox/src/components/RadioCard/RadioCard.tsx, packages/matchbox/src/components/RadioCard/styles.ts
- Removed :selected and :hover styles from small CheckboxCard and RadioCard
- Confirm hover and checked styles have been removed on small Card variants
=> UX-782 remove selected and hover states from small CheckboxCard and RadioCard

libby/feedback/Banner.lib.tsx, libby/form/TextField.lib.tsx, packages/matchbox/src/components/TextField/TextField.tsx
- Adds control arrows for TextField with type="number"
- verify number TextField styles are correct and stepping up and down works by clicking the arrows and with keyboard control
=> UX-784 add arrow controls to Text Field with type 'number'

libby/form/Checkbox.lib.tsx, packages/matchbox/src/components/Checkbox/Checkbox.tsx
- Fixes a bug where controlled indeterminate checkboxes conflicting with uncontrolled behavior
- Visit: http://localhost:9001/?path=Checkbox__indeterminate-controlled
- Try clicking on the checkbox, it shouldnt show a check
=> Fix uncontrolled checked state conflicting with controlled indeterminate state

.changeset/short-beans-sparkle.md, .vscode/settings.json, packages/matchbox-icons/rollup/plugins/js.js, packages/matchbox-icons/tsconfig.json, packages/matchbox/rollup/plugins/js.js, packages/matchbox/tsconfig.json
- Temporarily removes the `terser` plugin. Was causing a `Error: kill EPERM` error. Need to find an alternative.
- Fixes the types compiled from the build scripts by changing tsconfig's base url. They were missing before. No idea why this works.
- Run `npm run build`
- Verify that the types are generated in `the dist` folders. Only affects `matchbox` and `matchbox-icons`
=> build: fix type compilation

packages/matchbox/src/components/TextField/TextField.tsx
- Go to TextField component
- Choose number options
- Check if onChange is now triggered when user clicks on input arrows.
1. Create a changeset with `npx changeset`
1. Ensure the changeset in the `.changeset` directory includes a descriptive summary
1. Commit the changeset to your pull request
=> SAZ-484 fix(TextField) number arrow not triggering change
